final Map<String, String> arTranslation = {
  "hotelbooking": "حجز الفندق",
  "skip": "يتخطى",
  "selectdestination": "حدد وجهتك...",
  "next": "التالي",
  "pickupyourtime": "التقاط وقتك ...",
  "enjoyyourtrip": "استمتع برحلتك...",
  "start": "يبدأ",
  "welcome": " أهلا بك",
  "haveaaccountsignin": "لديك حساب؟ تسجيل الدخول",
  "login": "تسجيل دخول",
  "signup": "اشتراك",
  "password": "كلمة المرور",
  "forgotpassword": "هل نسيت كلمة السر؟",
  "or": "أو",
  "donthaveanaccount": "ليس لديك حساب؟",
  "username": "اسم االمستخدم",
  "mobilenumber": "رقم الهاتف المحمول",
  "alreadyhaveanaccount": "هل لديك حساب؟",
  "send": "إرسال",
  "backtologin": "العودة إلى تسجيل الدخول",
  "verifyyouremail": "قم بتأكيد بريدك الألكتروني",
  "checkyourmail": "راجع بريدك",
  "wehavesentaotptoyourmailpleaseverify":
      "لقد أرسلنا OTP إلى البريد الخاص بك \n Please تحقق",
  "verify": "يؤكد",
  "createnewpassword": "إنشاء كلمة مرور جديدة",
  "newpassword": "كلمة مرور جديدة",
  "conformpassword": "تتوافق كلمة المرور",
  "save": "يحفظ",
  "choosethelanguage": "اختر اللغة",
  "english": "إنجليزي",
  "french": "الفرنسية",
  "gujarati": "الغوجاراتاتي",
  "germany": "ألمانيا",
  "italian": "الإيطالية",
  "belize": "بليز",
  "polish": "تلميع",
  "brazil": "البرازيل",
  "hithomas": "مرحبا توماس،",
  "findyourhotel": "ابحث عن فندقك",
  "trysingapore": "جرب سنغافورة",
  "nearyou": "بالقرب منك",
  "singapore": "سنغافورة",
  "turkey": "ديك رومى",
  "amsterdam": "أمستردام",
  "discover": "يكتشف",
  "viweall": "viwe جميعا",
  "visited": "زار",
  "india": "الهند",
  "grandhyatt": "جراند حياة",
  "onmap": "على الخريطة",
  "centralareasingapore": "المنطقة المركزية، سنغافورة",
  "carltoncityhotel": "فندق كارلتون سيتي",
  "km": "كم",
  "night": "ليل",
  "roomavailable": "غرفة متاحة",
  "details": "تفاصيل",
  "sheratonhotel": "فندق شيراتون",
  "maubstreetchicagoil": "Maub Street، شيكاغو، IL",
  "pernight": "لليلة الواحدة",
  "review": "مراجعة",
  "facilities": "خدمات",
  "wifi": "واي فاي",
  "gym": "نادي رياضي",
  "pool": "بركة سباحة",
  "restourant": "restourant.",
  "parking": "موقف سيارات",
  "itisalongestablishedfactthatareaderwillbeadistractedbythereadablecontentofapagewhenlookingatitslayoutthepointofusingloremofaipsumisthatithasamoreorlessnormalnormaldistributionofletters":
      "إنها حقيقة ثابتة منذ فترة طويلة أن القارئ سيكون مشتتا بواسطة المحتوى القابل للقراءة للصفحة عند النظر في تخطيطها. إن نقطة استخدام Lorem of A IPSum هي أنه يحتوي على توزيع طبيعي أكثر أو أقل طبيعية للأحرف.",
  "booknow": "احجز الآن",
  "jademountainhotel": "فندق جنين ماونتن",
  "price": "السعر",
  "search": " بحث",
  "booking": " الحجز",
  "standardsingleroom": "غرفة قياسية مفردة",
  "fastname": "اسم سريع",
  "lastname": "الكنية",
  "email": "بريد الالكتروني",
  "phoneno": "رقم الهاتف.",
  "arrival": "وصول",
  "departure": "مقال",
  "viewdetails": "عرض التفاصيل",
  "additionalservice": "خدمة اضافية",
  "spa": "منتجع صحي",
  "payment": "دفع",
  "onesingleroomnights": "ليالي غرفة واحدة واحدة",
  "total": "المجموع",
  "addnewaddress": "إضافة عنوان جديد",
  "homelocation": "موقع المنزل",
  "prospectsaintjamesbarbadosn/a": "احتمال، القديس جيمس، بربادوس ن / أ",
  "selectcard": "حدد بطاقة",
  "creditcard": "بطاقة ائتمان",
  "paypal": "باي بال",
  "applepay": "أبل الدفع",
  "pay": "يدفع",
  "addcreditcard": " أضف بطاقة الائتمان",
  "cardholdername": "إسم صاحب البطاقة",
  "stefanjohn": "ستيفان جون",
  "cardnumber": "رقم البطاقة",
  "cvv": "أفعى",
  "expirationdate": "تاريخ الإنتهاء",
  "securitycode": "رمز الحماية",
  "done": "منجز",
  "yourcardhasbeenaddedsuccessfully": "تمت إضافة بطاقتك بنجاح",
  "january": "كانون الثاني",
  "february": "شهر فبراير",
  "checkin": "تحقق في",
  "checkout": "الدفع",
  "jan": "في يناير",
  "grandcity": "مدينة جراند",
  "carltoncity": "مدينة كارلتون",
  "reviews": "تقييم",
  "thomashenderson": "توماس هندرسون",
  "des": "أمن",
  "loremipsumdolorsitametconsecteturadipiscingelitleonequeloremettortor":
      "Lorem Ipsum Dolor Sit Amet، Consectetur Adipiscing Elet. ليو نوك لوريم وآخرون.",
  "recommended": "مستحسن",
  "filter": "منقي",
  "reset": "إعادة ضبط",
  "category": "فئة",
  "all": "الجميع",
  "popular": "جمع",
  "sale": "تخفيض السعر",
  "luxury": "فخم. ترف",
  "pricerange": "نطاق السعر",
  "rating": "تقييم",
  "freewifi": "واى فاى مجانى",
  "parkingarea": "منطقة وقوف السيارات",
  "breakfirstmenu": "قائمة breakfirst",
  "bedroom": "غرفة نوم",
  "showresult": "نتيجة العرض",
  "notification": "تنبيه",
  "yourappoinmentisbooked": "تم حجز Appoinment الخاص بك",
  "min": "مين",
  "loremipsumissimplydummytextoftheprintingindustry":
      "Lorem Ipsum هو ببساطة نص دمية لصناعة الطباعة.",
  "hour": "ساعة",
  "hrs": "ساعة",
  "day": "يوم",
  "chooseroom": "اختر الغرفة",
  "freecoffee": "قهوة مجانية",
  "freebreakfast": "إفطار مجاني",
  "roseroom": "روز الغرفة",
  "ndfloor": "الكلمة الثانية",
  "loremipsumdolorsitametconsecteturadipiscingelitmuspurusdictumarcutinciduntsitetiamegetquammattisleomaurisdignissimturpisnibhatfeugiatblanditcursusfermentumultriciesnecnislnasceturturpisfacilisisodalesvariuslacuserosetiamturpisipsumvitaedonec":
      "Lorem Ipsum Dolor Sit Amet، Consectetur Adipiscing Elet. Mus Purus Dictum Arcutincidunt Sit Etiam Eget Quam. ماتيس ليو موريس، Dignissim Turpis Nibh. في Feugiac Blandit Cursus Fermentum Unlicies NEC NISL. Nascetur Turpis Facilisi Sodales Varius Lacus.eros Etiam Turpis Ipsum Vitae Donec.",
  "howlong": "حتى متى",
  "addreview": "إضافة مراجعة",
  "giveyourgrades": "إعطاء درجاتك",
  "whatdoyousay": "ماذا تقول ؟",
  "whatdoyouthink": "ما رأيك ؟",
  "notrecommended": "لا ينصح",
  "settings": "إعدادات",
  "basic": "الأساسي",
  "account": "حساب",
  "privacy&security": "الخصوصية و أمن",
  "location": "موقع",
  "darkmode": "الوضع المظلم",
  "more": "أكثر",
  "language": "لغة",
  "terms&condition": "الشروط والحالة",
  "customerservice": "خدمة العملاء",
  "signout": "خروج",
  "aboutus": "معلومات عنا",
  "contactinformation": "معلومات للتواصل",
  "companyaddress": "عنوان الشركة",
  "ithassurvivednotonlyfivecenturiesbutalsotheleapintoelectronictypesettingremainingessentiallyunchangeditwaspopularisedinthe1960swiththereleaseofletrasetsheetscontainingloremipsumpassagesandmorerecentlywithdesktoppublishingsoftwarelikealduspagemakerincludingversionsofloremipsum":
      "لقد نجا ليس فقط خمسة قرون، ولكن أيضا قفزة في التنضيد الإلكتروني، تبقى دون تغيير أساسا. تم شائعه في الستينيات من القرن الماضي مع إطلاق أوراق جدرراس التي تحتوي على ممرات Lorem Ipsum، ومؤخرا مع برنامج نشر سطح المكتب مثل Aldus PageMaker بما في ذلك إصدارات Lorem Ipsum.",
  "2privacypolicy": "2. سياسة الخصوصية",
  "utenimadminimaveniamquisnostrumexercitationnemullamcorporissuscipitlaboriosamnisiutaliquidexeacommodiconsequaturquisautemveleumiurereprehenderitquiineavoluptatevelitessequamnihilmolestiaeconsequaturvelillumquidoloremeumfugiatquovoluptasnullapariatur":
      "UT enim ad minima veniam، quis nostrum ممارسة ullam ullam corporis suscipit galleriosam، nisi ut aliquidex ea commodi mangatur؟ Quis Autem Vel Eum Iureprehenderit Qui في EA Velattate Velit Esse Quam Nihil Molestiae ماهيلات، فيل ريلوم Qui Dolorem Eum Fugiat Quo Voludtas Nulla Pariatur؟",
  "iagreewiththetermsandcondiition": "وأنا أتفق مع الشروط والتولي",
  "iagreewiththeprivacypolicy": "وأنا أتفق مع سياسة الخصوصية",
  "accept": "قبول",
  "decline": "انخفاض",
  "favourite": "المفضل",
  "thegreathyatt": "حياة كبيرة",
  "marinabaysingapore": "مارينا باي، سنغافورة",
  "paymentcompleted": "تم التسديد",
  "history": "تاريخ",
  "ritzcarlton": "الريتز كارلتون",
  "bandaseaindoneshia": "باندا البحر، إندونجيا",
  "bookagain": "احجز مرة أخرى",
  "support&faqs": "الدعم والأسئلة الشائعة",
  "hellohowcanwehelpyou": "أهلا! كيف يمكننا مساعدتك؟",
  "presstheheartbuttontoaddanhotel": "اضغط على زر القلب لإضافة فندق.",
  "paymentsanddiscountfees": "المدفوعات ورسوم الخصم",
  "totamremaperiam": " totam rem aperiam.",
  "sedquiaconsequunturmagni": " سيد كيا انبعث ماغن",
  "nequeporroquisquamest": "مؤسسة نوك بورو كوككام",
  "aliquamquaeratvoluptatem": "Aliquam Quaerat VoluttaTem.",
  "bookinginformation": "معلومات الحجز",
  "profile": "حساب تعريفي",
  "johnblake": " جون بليك",
  "editprofile": "تعديل الملف الشخصي",
  "basicdetail": "التفاصيل الأساسية",
  "name": "اسم",
  "dateofbirth": "تاريخ الميلاد",
  "phonenumber": "رقم التليفون",
  "male": "ذكر",
  "female": "أنثى",
  "filters": "مرشحات",
  "ridehistory": "ركوب التاريخ",
  "help": "مساعدة",
  "logout": "تسجيل خروج",
  "favoriteplaceinthearea": "المكان المفضل في المنطقة",
  "reviewdetail": "مراجعة التفاصيل",
  "wedjan": "الأربعاء يناير",
  "thujan": "ثو يناير",
  "jhondoe": "جون دو",
  "enterthepasswordforsecureyouraccount":
      "أدخل كلمة المرور لحساب Secure \n your.",
  "entertheemailaddressassociatedwithyouraccount":
      "أدخل عنوان البريد الإلكتروني المرتبط بحسابك.",
  "backto": "ارجع الى",
  "register": "يسجل",
  "leaseenteravalidfirstname": "الإيجار أدخل الاسم الأول صالح",
  "pleaseenteravalidlastname": "رجاء قم بإدخال الاسم الاخير بشكل صحيح",
  "pleaseenteravalidemailaddress": "يرجى إدخال عنوان بريد إلكتروني صالح",
  "pleaseenteravalidphoneno": "الرجاء إدخال رقم هاتف صالح",
  "pleaseselectdate": "يرجى اختيار التاريخ",
  "restaurant": "مطعم",
  "onesingleroomx2nights": "غرفة واحدة واحدة × 2 ليال",
  "menu": "قائمة",
  "favorite": "مفضل",
  "seeall": "اظهار الكل",
  "pleaseenteravalidusername": "الرجاءادخال اسم مستخدم صحيح",
  "pleaseenteradateofbirth": "الرجاء إدخال تاريخ الميلاد",
  "pleaseentervalidmobilenumber": "الرجاء إدخال رقم الجوال صالح",
  "myprofile": "ملفي",
  "views": "الآراء",
  "selectyourpreferredlanguage": "حدد لغتك المفضلة",
  "confirmlanguage": "تأكيد اللغة",
  "termsandcondition": "أحكام وشروط",
  "privacypolicy": "سياسة خاصة",
};
