final Map<String, String> enTranslation = {
  "hotelbooking": "Hotel Booking ",
  "skip": "Skip",
  "selectdestination": "Select Destination...",
  "next": "Next",
  "pickupyourtime": "Pick up Your Time...",
  "enjoyyourtrip": "Enjoy Your Trip...",
  "start": "Start",
  "welcome": " Welcome",
  "haveaaccountsignin": "Have a account? Sign In",
  "login": "Log In",
  "signup": "Sign Up",
  "password": "Password",
  "forgotpassword": "Forgot Password",
  "or": "Or",
  "donthaveanaccountregister": "Don't Have an Account?",
  "username": "User Name",
  "mobilenumber": "Mobile Number",
  "alreadyhaveanaccountlogin": "Already Have an Account?",
  "send": "send",
  "backtologin": "Back to login",
  "verifyyouremail": "Verify Your Email",
  "checkyourmail": "Check Your Mail",
  "wehavesentaotptoyourmailpleaseverify":
      "We have sent a OTP to your mail please verify",
  "verify": "Verify",
  "createnewpassword": "Create New Password",
  "newpassword": "New Password",
  "conformpassword": "Conform Password",
  "save": "Save",
  "choosethelanguage": "Choose the language",
  "english": "English",
  "french": "French",
  "gujarati": "Gujarati",
  "germany": "Germany",
  "italian": "Italian",
  "belize": "Belize",
  "polish": "Polish",
  "brazil": "Brazil",
  "hithomas": "Hi Thomas,",
  "findyourhotel": "Find Your Hotel",
  "trysingapore": "Try “Singapore”",
  "nearyou": "Near You",
  "singapore": "Singapore",
  "turkey": "Turkey",
  "amsterdam": "Amsterdam",
  "discover": "Discover",
  "viweall": "Viwe All",
  "visited": "Visited",
  "india": "India",
  "grandhyatt": "Grand Hyatt",
  "onmap": "On Map",
  "centralareasingapore": "Central Area, Singapore",
  "carltoncityhotel": "Carlton City Hotel",
  "km": "km",
  "night": "Night",
  "roomavailable": "Room Available",
  "details": "Details",
  "sheratonhotel": "Sheraton Hotel",
  "maubstreetchicagoil": "Maub Street, Chicago, IL",
  "pernight": "per night",
  "review": "Review",
  "facilities": "Facilities",
  "wifi": "Wifi",
  "gym": "Gym",
  "pool": "Pool",
  "restourant": "Restourant",
  "parking": "Parking",
  "itisalongestablishedfactthatareaderwillbeadistractedbythereadablecontentofapagewhenlookingatitslayoutthepointofusingloremofaipsumisthatithasamoreorlessnormalnormaldistributionofletters":
      "It is a long established fact that a reader will be a distracted by the readable content of a page when looking at its layout. The point of  using Lorem of a  Ipsum is that it has a more or-less normal  normal distribution of letters.",
  "booknow": "Book Now",
  "jademountainhotel": "Jade Mountain Hotel",
  "price": "Price",
  "search": " Search",
  "booking": " Booking",
  "standardsingleroom": "Standard Single Room",
  "fastname": "Fast Name",
  "lastname": "Last Name",
  "email": "Email",
  "phoneno": "Phone No.",
  "arrival": "Arrival ",
  "departure": "Departure",
  "viewdetails": "View Details",
  "additionalservice": "Additional Service",
  "spa": "Spa",
  "payment": "Payment",
  "onesingleroomnights": "One Single Room nights",
  "total": "Total",
  "addnewaddress": "Add New Address",
  "homelocation": "Home Location",
  "prospectsaintjamesbarbadosn/a": "Prospect, Saint James, Barbados N/A",
  "selectcard": "Select Card",
  "creditcard": "Credit Card",
  "paypal": "PayPal",
  "applepay": "Apple Pay",
  "pay": "Pay",
  "addcreditcard": " Add credit Card",
  "cardholdername": "Cardholder Name",
  "stefanjohn": "Stefan John",
  "cardnumber": "Card Number",
  "cvv": "CVV",
  "expirationdate": "Expiration Date",
  "securitycode": "Security Code",
  "done": "Done",
  "yourcardhasbeenaddedsuccessfully": "Your card has been added successfully",
  "january": "January",
  "february": "February",
  "checkin": "Check In",
  "checkout": "Check Out",
  "jan": "Jan",
  "grandcity": "Grand City",
  "carltoncity": "Carlton City",
  "reviews": "Reviews",
  "thomashenderson": "Thomas Henderson",
  "des": "Des",
  "loremipsumdolorsitametconsecteturadipiscingelitleonequeloremettortor":
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Leo neque lorem et tortor.",
  "recommended": "Recommended",
  "filter": "Filter",
  "reset": "Reset",
  "category": "Category",
  "all": "All",
  "popular": "Popular",
  "sale": "Sale",
  "luxury": "Luxury",
  "pricerange": "Price Range",
  "rating": "Rating",
  "freewifi": "Free Wifi",
  "parkingarea": "Parking Area",
  "breakfirstmenu": "Breakfirst Menu",
  "bedroom": "Bedroom",
  "showresult": "Show Result",
  "notification": "Notification",
  "yourappoinmentisbooked": "Your Appoinment is Booked",
  "min": "min",
  "loremipsumissimplydummytextoftheprintingindustry":
      "Lorem Ipsum is simply dummy text of the printing industry.",
  "hour": "Hour",
  "hrs": "Hrs",
  "day": "Day",
  "chooseroom": "Choose Room",
  "freecoffee": "Free Coffee",
  "freebreakfast": "Free Breakfast",
  "roseroom": "Rose Room",
  "ndfloor": "nd Floor",
  "loremipsumdolorsitametconsecteturadipiscingelitmuspurusdictumarcutinciduntsitetiamegetquammattisleomaurisdignissimturpisnibhatfeugiatblanditcursusfermentumultriciesnecnislnasceturturpisfacilisisodalesvariuslacuserosetiamturpisipsumvitaedonec":
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mus purus dictum arcutincidunt sit etiam eget quam. Mattis leo mauris, dignissim turpis nibh. At feugiat blandit cursus fermentum ultricies nec nisl. Nascetur turpis facilisi sodales varius lacus.Eros etiam turpis ipsum vitae donec.",
  "howlong": "How Long",
  "addreview": "Add Review",
  "giveyourgrades": "Give Your Grades",
  "whatdoyousay": "What do you say ?",
  "whatdoyouthink": "What do you think ?",
  "notrecommended": "Not Recommended",
  "settings": "Settings",
  "basic": "Basic",
  "account": "Account",
  "privacy&security": "Privacy & Security",
  "location": "Location",
  "darkmode": "Dark Mode",
  "more": "More",
  "language": "Language",
  "terms&condition": "Terms & Condition",
  "customerservice": "Customer Service",
  "signout": "Sign Out",
  "aboutus": "About us",
  "contactinformation": "Contact information",
  "companyaddress": "Company Address",
  "utenimadminimaveniamquisnostrumexercitationnemullamcorporissuscipitlaboriosamnisiutaliquidexeacommodiconsequaturquisautemveleumiurereprehenderitquiineavoluptatevelitessequamnihilmolestiaeconsequaturvelillumquidoloremeumfugiatquovoluptasnullapariatur":
      "Ut enim ad minima veniam, quis nostrum exercitationnem ullam corporis suscipit laboriosam, nisi ut aliquidex ea commodi consequatur? Quis autem vel eum iurereprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
  "iagreewiththetermsandcondiition": "I agree with the Terms and condiition",
  "iagreewiththeprivacypolicy": "I agree with the Privacy Policy",
  "accept": "Accept",
  "decline": "Decline",
  "favourite": "Favourite",
  "thegreathyatt": "The Great Hyatt",
  "marinabaysingapore": "Marina bay, Singapore",
  "paymentcompleted": "Payment completed",
  "history": "History",
  "ritzcarlton": "Ritz-Carlton",
  "bandaseaindoneshia": "Banda sea, Indoneshia",
  "bookagain": "Book again ",
  "support&faqs": "Support & FAQs",
  "hellohowcanwehelpyou": "Hello! How can we help you?",
  "presstheheartbuttontoaddanhotel": "Press the heart button to add an hotel. ",
  "paymentsanddiscountfees": "Payments and Discount Fees",
  "totamremaperiam": " Totam rem aperiam",
  "sedquiaconsequunturmagni": " Sed quia consequuntur magni",
  "nequeporroquisquamest": "Neque porro quisquam est",
  "aliquamquaeratvoluptatem": "Aliquam quaerat voluptatem",
  "bookinginformation": "Booking Information",
  "profile": "Profile",
  "johnblake": " John Blake",
  "editprofile": "Edit Profile",
  "basicdetail": "Basic Detail",
  "name": "Name",
  "dateofbirth": "Date of Birth",
  "phonenumber": "Phone Number",
  "male": "Male",
  "female": "Female",
  "filters": "Filters",
  "ridehistory": "Ride History",
  "help": "Help",
  "logout": "Logout",
  "favoriteplaceinthearea": "Favorite place in the area",
  "reviewdetail": "Review Detail",
  "wedjan": "Wed Jan",
  "thujan": "Thu Jan",
  "jhondoe": "Jhon Doe",
  "enterthepasswordforsecureyouraccount":
      "Enter the password for secure\nyour account.",
  "entertheemailaddressassociatedwithyouraccount":
      "Enter the email address associated with your account.",
  "backto": "Back to",
  "register": "Register",
  "leaseenteravalidfirstname": "lease Enter a Valid First Name",
  "pleaseenteravalidlastname": "Please Enter a Valid Last Name",
  "pleaseenteravalidemailaddress": "Please Enter a Valid Email Address",
  "pleaseenteravalidphoneno": "Please Enter a Valid Phone No.",
  "pleaseselectdate": "Please Select Date",
  "restaurant": "Restaurant",
  "onesingleroomx2nights": "One Single Room x 2 nights",
  "menu": "menu",
  "favorite": "Favorite",
  "seeall": "See all",
  "pleaseenteravalidusername": "Please enter a valid username",
  "pleaseenteradateofbirth": "Please enter a Date of Birth",
  "pleaseentervalidmobilenumber": "Please Enter Valid Mobile Number",
  "myprofile": "My Profile",
  "views": "Views",
  "selectyourpreferredlanguage": "Select your preferred Language",
  "confirmlanguage": "Confirm Language",
  "termsandcondition": "Terms and Condition",
  "privacypolicy": "Privacy Policy",
};
