final Map<String, String> esTranslation = {
  "hotelbooking": "Reserva de hotel",
  "skip": "Saltar",
  "selectdestination": "Seleccione Destino ...",
  "next": "Próximo",
  "pickupyourtime": "Recoge tu tiempo ...",
  "enjoyyourtrip": "Disfruta tu viaje...",
  "start": "Comienzo",
  "welcome": " Bienvenidos",
  "haveaaccountsignin": "Tener una cuenta? Iniciar sesión",
  "login": "Iniciar sesión",
  "signup": "Inscribirse",
  "password": "Clave",
  "forgotpassword": "¿Has olvidado tu contraseña?",
  "or": "O",
  "donthaveanaccount": "¿No tienes una cuenta?",
  "username": "Nombre de usuario",
  "mobilenumber": "Número de teléfono móvil",
  "alreadyhaveanaccount": "¿Ya tienes una cuenta?",
  "send": "enviar",
  "backtologin": "Atrás para iniciar sesión",
  "verifyyouremail": "Verifique su correo electrónico",
  "checkyourmail": "Revisa tu correo",
  "wehavesentaotptoyourmailpleaseverify":
      "Hemos enviado una OTP a su correo \n PLEase Verifique",
  "verify": "Verificar",
  "createnewpassword": "Crear nueva contraseña",
  "newpassword": "Nueva contraseña",
  "conformpassword": "Conformar contraseña",
  "save": "Salvar",
  "choosethelanguage": "Elige el idioma",
  "english": "inglés",
  "french": "francés",
  "gujarati": "Gujarati",
  "germany": "Alemania",
  "italian": "italiano",
  "belize": "Belice",
  "polish": "polaco",
  "brazil": "Brasil",
  "hithomas": "Hola Thomas,",
  "findyourhotel": "Encuentra tu hotel",
  "trysingapore": "Prueba Singapur",
  "nearyou": "Cerca de usted",
  "singapore": "Singapur",
  "turkey": "pavo",
  "amsterdam": "Amsterdam",
  "discover": "Descubrir",
  "viweall": "Viwe all",
  "visited": "Visitó",
  "india": "India",
  "grandhyatt": "Grand Hyatt",
  "onmap": "En mapa",
  "centralareasingapore": "Área Central, Singapur",
  "carltoncityhotel": "Hotel Carlton City",
  "km": "km",
  "night": "Noche",
  "roomavailable": "Habitación disponible",
  "details": "Detalles",
  "sheratonhotel": "hotel Sheraton",
  "maubstreetchicagoil": "Maub Street, Chicago, IL",
  "pernight": "por noche",
  "review": "Revisar",
  "facilities": "Instalaciones",
  "wifi": "Wifi",
  "gym": "Gimnasio",
  "pool": "Piscina",
  "restourant": "Restaurante",
  "parking": "Estacionamiento",
  "itisalongestablishedfactthatareaderwillbeadistractedbythereadablecontentofapagewhenlookingatitslayoutthepointofusingloremofaipsumisthatithasamoreorlessnormalnormaldistributionofletters":
      "Es un hecho largo establecido de que un lector será distraído por el contenido legible de una página al mirar su diseño. El punto de usar Lorem de un IPSUM es que tiene una distribución normal más o menos normal de las letras.",
  "booknow": "Reservar ahora",
  "jademountainhotel": "Jade Mountain Hotel",
  "price": "Precio",
  "search": " Búsqueda",
  "booking": " Reserva",
  "standardsingleroom": "Habitación individual estándar",
  "fastname": "Nombre rápido",
  "lastname": "Apellido",
  "email": "Correo electrónico",
  "phoneno": "Telefono no.",
  "arrival": "Llegada",
  "departure": "Salida",
  "viewdetails": "Ver detalles",
  "additionalservice": "Servicio adicional",
  "spa": "Spa",
  "payment": "Pago",
  "onesingleroomnights": "Una sola habitación noches",
  "total": "Total",
  "addnewaddress": "Agregar nueva dirección",
  "homelocation": "Localización de la casa",
  "prospectsaintjamesbarbadosn/a": "PROSPECTO, SAINT JAMES, BARBADOS N / A",
  "selectcard": "Seleccione la tarjeta",
  "creditcard": "Tarjeta de crédito",
  "paypal": "Paypal",
  "applepay": "Pago de manzana",
  "pay": "Pagar",
  "addcreditcard": " Añadir tarjeta de crédito",
  "cardholdername": "Nombre del titular de la tarjeta",
  "stefanjohn": "Stefan John",
  "cardnumber": "Número de tarjeta",
  "cvv": "Cvv",
  "expirationdate": "Fecha de caducidad",
  "securitycode": "Código de seguridad",
  "done": "Hecho",
  "yourcardhasbeenaddedsuccessfully": "Su tarjeta ha sido añadida con éxito.",
  "january": "enero",
  "february": "febrero",
  "checkin": "Registrarse",
  "checkout": "Verificar",
  "jan": "ene",
  "grandcity": "Gran ciudad",
  "carltoncity": "Ciudad de Carlton",
  "reviews": "Comentarios",
  "thomashenderson": "Thomas Henderson",
  "des": "Des",
  "loremipsumdolorsitametconsecteturadipiscingelitleonequeloremettortor":
      "Lorem Ipsum Dolors Sit AMet, ConsecteTur Adipiscing Elit. Leo Neque Lorem et tortor.",
  "recommended": "Recomendado",
  "filter": "Filtrar",
  "reset": "Reiniciar",
  "category": "Categoría",
  "all": "Todos",
  "popular": "Popular",
  "sale": "Rebaja",
  "luxury": "Lujo",
  "pricerange": "Rango de precios",
  "rating": "Clasificación",
  "freewifi": "Wi-Fi gratis",
  "parkingarea": "Aparcamiento",
  "breakfirstmenu": "Menú de breakfirst",
  "bedroom": "Habitación",
  "showresult": "Mostrar resultado",
  "notification": "Notificación",
  "yourappoinmentisbooked": "Tu apartamento se reserva",
  "min": "minuto",
  "loremipsumissimplydummytextoftheprintingindustry":
      "Lorem Ipsum es simplemente texto ficticio de la industria de la impresión.",
  "hour": "Hora",
  "hrs": "Horas",
  "day": "Día",
  "chooseroom": "Elegir sala",
  "freecoffee": "Café gratis",
  "freebreakfast": "Desayuno gratis",
  "roseroom": "Sala de rosas",
  "ndfloor": "piso de ND",
  "loremipsumdolorsitametconsecteturadipiscingelitmuspurusdictumarcutinciduntsitetiamegetquammattisleomaurisdignissimturpisnibhatfeugiatblanditcursusfermentumultriciesnecnislnasceturturpisfacilisisodalesvariuslacuserosetiamturpisipsumvitaedonec":
      "Lorem Ipsum Dolors Sit AMet, ConsecteTur Adipiscing Elit. Mus Purus Dictum Arc ARCUTINGIDUNT SIT ETIAM ETGE CIVAM. Mattis Leo Mauris, Dignissim Turpis Nibh. En Feugiat Blandit Cursus Fermentum Ultricies NEC NISL. NASCETUR TURPIS FACILISI SODALES VARIUS LACUS.EROS ETIAM TURPIS IPSUM VITAE DONEC.",
  "howlong": "Cuánto tiempo",
  "addreview": "Agregar una opinión",
  "giveyourgrades": "Dale a tus calificaciones",
  "whatdoyousay": "Qué dices ?",
  "whatdoyouthink": "Qué piensas ?",
  "notrecommended": "No recomendado",
  "settings": "Ajustes",
  "basic": "Básico",
  "account": "Cuenta",
  "privacy&security": "Privacidad y seguridad",
  "location": "Ubicación",
  "darkmode": "Modo oscuro",
  "more": "Más",
  "language": "Idioma",
  "terms&condition": "Términos y Condiciones",
  "customerservice": "Servicio al Cliente",
  "signout": "Desconectar",
  "aboutus": "Sobre nosotros",
  "contactinformation": "Información del contacto",
  "companyaddress": "Dirección de la empresa",
  "ithassurvivednotonlyfivecenturiesbutalsotheleapintoelectronictypesettingremainingessentiallyunchangeditwaspopularisedinthe1960swiththereleaseofletrasetsheetscontainingloremipsumpassagesandmorerecentlywithdesktoppublishingsoftwarelikealduspagemakerincludingversionsofloremipsum":
      "Ha sobrevivido no solo cinco siglos, sino también el salto en la tipografía electrónica, permaneciendo esencialmente sin cambios. Fue popularizado en la década de 1960 con la liberación de hojas de letraset que contienen pasajes de Lorem Ipsum, y más recientemente con el software de publicación de escritorio como Aldus PageMaker, incluidas las versiones de Lorem Ipsum.",
  "2privacypolicy": "2. Política de privacidad",
  "utenimadminimaveniamquisnostrumexercitationnemullamcorporissuscipitlaboriosamnisiutaliquidexeacommodiconsequaturquisautemveleumiurereprehenderitquiineavoluptatevelitessequamnihilmolestiaeconsequaturvelillumquidoloremeumfugiatquovoluptasnullapariatur":
      "UT ENIM AD MINIMA VENIAM, DESSIUM EJERCINO DE QUIS NOSTRUM EXTRIVE ULLAM Corporis Soscipit Laboriosam, NISI UT Aliquidex EA COMMODI SHEARTUR? Quis Autem Vel Eum IurerePrehenderit qui en EA voluptate Velit Esse Quam Nihil Molestiae Semberatur, Vel Illum Qui Dolorem Eum Fugiat quo Voluptras Nulla Pariature?",
  "iagreewiththetermsandcondiition":
      "Estoy de acuerdo con los Términos y Condiition",
  "iagreewiththeprivacypolicy":
      "Estoy de acuerdo con la Política de privacidad.",
  "accept": "Aceptar",
  "decline": "Disminución",
  "favourite": "Favorito",
  "thegreathyatt": "El gran hyatt",
  "marinabaysingapore": "Marina Bay, Singapur",
  "paymentcompleted": "Pago completado",
  "history": "Historia",
  "ritzcarlton": "Ritz-carlton",
  "bandaseaindoneshia": "Banda Mar, Indoneshia",
  "bookagain": "Reservar de nuevo",
  "support&faqs": "Soporte y Preguntas Frecuentes",
  "hellohowcanwehelpyou": "¡Hola! como podemos ayudarte?",
  "presstheheartbuttontoaddanhotel":
      "Presiona el botón del corazón para agregar un hotel.",
  "paymentsanddiscountfees": "Pagos y tarifas de descuento.",
  "totamremaperiam": " Totam REM APERIAM",
  "sedquiaconsequunturmagni": " SED QUIA consecuente Magni",
  "nequeporroquisquamest": "Neque porro quisquam est",
  "aliquamquaeratvoluptatem": "Aliquam quaerat voluptatem",
  "bookinginformation": "Información de la reserva",
  "profile": "Perfil",
  "johnblake": " John Blake",
  "editprofile": "Editar perfil",
  "basicdetail": "Detalle básico",
  "name": "Nombre",
  "dateofbirth": "Fecha de nacimiento",
  "phonenumber": "Número de teléfono",
  "male": "Masculino",
  "female": "Mujer",
  "filters": "Filtros",
  "ridehistory": "Historia de viaje",
  "help": "Ayuda",
  "logout": "Cerrar sesión",
  "favoriteplaceinthearea": "Lugar favorito en la zona.",
  "reviewdetail": "Detalle de revisión",
  "wedjan": "Miércoles",
  "thujan": "Janero",
  "jhondoe": "Jhon doe",
  "enterthepasswordforsecureyouraccount":
      "Ingrese la contraseña para la cuenta segura \n YOUR.",
  "entertheemailaddressassociatedwithyouraccount":
      "Ingrese la dirección de correo electrónico asociada con su cuenta.",
  "backto": "De regreso",
  "register": "Registrarse",
  "leaseenteravalidfirstname": "Arrendamiento Ingrese un nombre válido",
  "pleaseenteravalidlastname": "Por favor ingrese un apellido válido",
  "pleaseenteravalidemailaddress":
      "Por favor, introduce una dirección de correo electrónico válida",
  "pleaseenteravalidphoneno": "Por favor ingrese un número de teléfono válido",
  "pleaseselectdate": "Por favor, seleccione la fecha",
  "restaurant": "Restaurante",
  "onesingleroomx2nights": "Una habitación individual x 2 noches",
  "menu": "menú",
  "favorite": "Favorito",
  "seeall": "Ver todo",
  "pleaseenteravalidusername": "Por favor ingrese un nombre de usuario válido",
  "pleaseenteradateofbirth": "Por favor ingrese una fecha de nacimiento",
  "pleaseentervalidmobilenumber":
      "Por favor, introduzca un número de móvil válido",
  "myprofile": "Mi perfil",
  "views": "Puntos de vista",
  "selectyourpreferredlanguage": "Seleccione su idioma preferido",
  "confirmlanguage": "Confirmar idioma",
  "termsandcondition": "Términos y Condiciones",
  "privacypolicy": "Política de privacidad",
};
