final Map<String, String> etTranslation = {
  "hotelbooking":"HOIDU",
"skip":"Vahele jätma",
"selectdestination":"Valige sihtkoht ...",
"next":"Järgmine",
"pickupyourtime":"Korja oma aega ...",
"enjoyyourtrip":"Naudi oma reisi...",
"start":"Alustama",
"welcome":" Tere tulemast",
"haveaaccountsignin":"Kas kontol on konto? Logi sisse",
"login":"Logi sisse",
"signup":"Registreeri",
"password":"Parool",
"forgotpassword":"Unustasid parooli?",
"or":"Või",
"donthaveanaccount":"Kas teil pole kontot?",
"username":"Kasutajanimi",
"mobilenumber":"Mobiili number",
"alreadyhaveanaccount":"On juba konto?",
"send":"saada",
"backtologin":"Tagasi sisselogimiseks",
"verifyyouremail":"Kontrollige oma e-posti",
"checkyourmail":"Kontrolli oma e-posti",
"wehavesentaotptoyourmailpleaseverify":"Oleme saatnud OTP oma e-kirjale",
"verify":"Kontrollima",
"createnewpassword":"Loo uus parool",
"newpassword":"uus salasõna",
"conformpassword":"Parool",
"save":"Säästa",
"choosethelanguage":"Valige keel",
"english":"Inglise",
"french":"Prantsuse keel",
"gujarati":"Gujarati",
"germany":"Saksamaa",
"italian":"Itaalia keel",
"belize":"Belize",
"polish":"Poola",
"brazil":"Brasiilia",
"hithomas":"Tere Thomas,",
"findyourhotel":"Leia oma hotell",
"trysingapore":"Proovi Singapur",
"nearyou":"Sinu lähedal",
"singapore":"Singapur",
"turkey":"Türgi",
"amsterdam":"Amsterdam",
"discover":"Avastama",
"viweall":"Viwe kõik",
"visited":"Külastatud",
"india":"India",
"grandhyatt":"Grand Hyatt",
"onmap":"Kaardil",
"centralareasingapore":"Keskpiirkond, Singapur",
"carltoncityhotel":"Carlton City hotell",
"km":"km",
"night":"Öösel",
"roomavailable":"Saadaval tuba",
"details":"Üksikasjad",
"sheratonhotel":"Sheraton hotell",
"maubstreetchicagoil":"Maub Street, Chicago, Il",
"pernight":"öö kohta",
"review":"Ülevaade",
"facilities":"Rajatised",
"wifi":"Wifi",
"gym":"Jõusaal",
"pool":"Bassein",
"restourant":"Restaurant",
"parking":"Parkimine",
"itisalongestablishedfactthatareaderwillbeadistractedbythereadablecontentofapagewhenlookingatitslayoutthepointofusingloremofaipsumisthatithasamoreorlessnormalnormaldistributionofletters":"On kaua kindlaks tehtud asjaolu, et lugeja on selle paigutuse vaatamise ajal häiritud lehe loetav sisu. Ipsum Loremi kasutamise punkt on see, et sellel on tähtede enam-vähem tavaline tavaline jaotus.",
"booknow":"Broneeri kohe",
"jademountainhotel":"Jade Mountain Hotel",
"price":"Hind",
"search":" Otsing",
"booking":" Broneerimine",
"standardsingleroom":"Standard üheinimesetuba",
"fastname":"Kiire nimi",
"lastname":"Perekonnanimi",
"email":"E-kiri",
"phoneno":"Telefoni number",
"arrival":"Saabumine",
"departure":"Lahkumine",
"viewdetails":"Vaata detaile",
"additionalservice":"Lisateenus",
"spa":"Spaa",
"payment":"Maksmine",
"onesingleroomnights":"Üks üheinimesetuba ööd",
"total":"Kogusumma",
"addnewaddress":"Lisa uus aadress",
"homelocation":"Avaleht Asukoht",
"prospectsaintjamesbarbadosn/a":"Prospect, Saint James, Barbados N / A",
"selectcard":"Vali kaart",
"creditcard":"Krediitkaart",
"paypal":"Paypal",
"applepay":"Apple'i tasu",
"pay":"Maksma",
"addcreditcard":" Lisa krediitkaart",
"cardholdername":"Kaardi valdaja nimi",
"stefanjohn":"Stefan John",
"cardnumber":"Kaardi number",
"cvv":"Cvv",
"expirationdate":"Aegumiskuupäev",
"securitycode":"Turvakood",
"done":"Valmis",
"yourcardhasbeenaddedsuccessfully":"Teie kaart on edukalt lisatud",
"january":"Jaanuar",
"february":"Veebruar",
"checkin":"Kontrollima",
"checkout":"Kontrollima",
"jan":"Jan",
"grandcity":"Suurlinn",
"carltoncity":"Carlton City",
"reviews":"Arvamused",
"thomashenderson":"Thomas Henderson",
"des":"Des",
"loremipsumdolorsitametconsecteturadipiscingelitleonequeloremettortor":"LOREM IPSUM DOLOR SITE Amet, Consictur Adipicing Elit. Leo naque lorem et kilotor.",
"recommended":"Soovitatav",
"filter":"Filtreerima",
"reset":"Lähtestama",
"category":"Kategooria",
"all":"Kõik",
"popular":"Populaarne",
"sale":"Soodustus",
"luxury":"Luksuslik",
"pricerange":"Hinnavahemik",
"rating":"Hinnang",
"freewifi":"Tasuta WiFi-ühendus",
"parkingarea":"Parkimisala",
"breakfirstmenu":"Menüü BreakFirst",
"bedroom":"Magamistuba",
"showresult":"Näitama tulemus",
"notification":"Teatis",
"yourappoinmentisbooked":"Teie appoinment on broneeritud",
"min":"min",
"loremipsumissimplydummytextoftheprintingindustry":"LOREM IPSUM on lihtsalt trükitööstuse näiv tekst.",
"hour":"Tunde",
"hrs":"Hrs",
"day":"Päev",
"chooseroom":"Vali tuba",
"freecoffee":"Tasuta kohv",
"freebreakfast":"Tasuta hommikusöök",
"roseroom":"Roosituba",
"ndfloor":"ND Floor",
"loremipsumdolorsitametconsecteturadipiscingelitmuspurusdictumarcutinciduntsitetiamegetquammattisleomaurisdignissimturpisnibhatfeugiatblanditcursusfermentumultriciesnecnislnasceturturpisfacilisisodalesvariuslacuserosetiamturpisipsumvitaedonec":"LOREM IPSUM DOLOR SITE Amet, Consictur Adipicing Elit. Mus Purus Dictum Arcutincidunt Sit ETIAM eGEt Quam. Mattis Leo Mauris, DigisSim Turpis Nibh. At Feugiat Blandit Cursus Fermentum Ultricial NEC NISL. Nascetur Turpis Faborsi Sodales Varius Lacus.eros EtIAM Turpis Ipsum Vitae Donec.",
"howlong":"Kui kaua",
"addreview":"Lisa ülevaade",
"giveyourgrades":"Anna oma klassid",
"whatdoyousay":"Mida sa ütled ?",
"whatdoyouthink":"Mida sa arvad ?",
"notrecommended":"Ei soovitata",
"settings":"Seaded",
"basic":"Põhi-",
"account":"Konto",
"privacy&security":"Privaatsus ja turvalisus",
"location":"Asukoht",
"darkmode":"Tume režiim",
"more":"Rohkem",
"language":"Keel",
"terms&condition":"Tingimused ja seisund",
"customerservice":"Kasutajatugi",
"signout":"Logi välja",
"aboutus":"Meist",
"contactinformation":"Kontaktinfo",
"companyaddress":"ettevõtte aadress",
"ithassurvivednotonlyfivecenturiesbutalsotheleapintoelectronictypesettingremainingessentiallyunchangeditwaspopularisedinthe1960swiththereleaseofletrasetsheetscontainingloremipsumpassagesandmorerecentlywithdesktoppublishingsoftwarelikealduspagemakerincludingversionsofloremipsum":"See on säilinud mitte ainult viis sajandit, vaid ka hüpe elektroonilisele trükkimisele, jäädes sisuliselt muutumatuks. See populariseeriti 1960ndatel vabanemisega LORSEt Lehtede sisaldavad Lorem Ipsum Passages ja hiljuti töölaua kirjastamine tarkvara nagu ALDUS PAGEMAKER, sealhulgas LOREM IPSUM versioonid.",
"2privacypolicy":"2. Privaatsuspoliitika",
"utenimadminimaveniamquisnostrumexercitationnemullamcorporissuscipitlaboriosamnisiutaliquidexeacommodiconsequaturquisautemveleumiurereprehenderitquiineavoluptatevelitessequamnihilmolestiaeconsequaturvelillumquidoloremeumfugiatquovoluptasnullapariatur":"Ut Enim Ad Minima Veniam, Quis Nostrum Harjutusmene Ullam Corresis Suscipit Workioioram, Nisi Ut Aliquidex EA kaubamaa tagastus? Quis Aitem Vel Eum iurerepreheritit qui Ea Visupad Velit Esse Quam Nihil Molestiae tagajärg, Vel Illum qui dolorem Eum Fugia quo Volupas Nulla PariaTur?",
"iagreewiththetermsandcondiition":"Nõustun tingimustega ja kontensiooniga",
"iagreewiththeprivacypolicy":"Nõustun privaatsuspoliitikaga",
"accept":"Vastu võtma",
"decline":"Langus",
"favourite":"Lemmik",
"thegreathyatt":"Suur Hyatt",
"marinabaysingapore":"Marina Bay, Singapur",
"paymentcompleted":"Makse lõpetatud",
"history":"Ajalugu",
"ritzcarlton":"Ritz-Carlton",
"bandaseaindoneshia":"Banda meri, indoneshia",
"bookagain":"Broneeri uuesti",
"support&faqs":"Toetus ja KKK",
"hellohowcanwehelpyou":"Tere! Kuidas me saame teid aidata?",
"presstheheartbuttontoaddanhotel":"Hotelli lisamiseks vajutage südame nuppu.",
"paymentsanddiscountfees":"Maksed ja soodushinnaga tasud",
"totamremaperiam":" Totam REM Aperiam",
"sedquiaconsequunturmagni":" SED QUIA tagajärgi Magnani",
"nequeporroquisquamest":"Neque porro quisquam est",
"aliquamquaeratvoluptatem":"Aliquam Quaerat Voluseti",
"bookinginformation":"Broneeringuteave",
"profile":"Profiil",
"johnblake":" John Blake",
"editprofile":"Muuda profiili",
"basicdetail":"Põhiteade",
"name":"Nimetus",
"dateofbirth":"Sünnikuupäev",
"phonenumber":"Telefoninumber",
"male":"Mees",
"female":"Naissoost",
"filters":"Filtrid",
"ridehistory":"Ajalugu",
"help":"Aitama",
"logout":"Logi välja",
"favoriteplaceinthearea":"Lemmik koht piirkonnas",
"reviewdetail":"Üksikasjad",
"wedjan":"Wed Jan",
"thujan":"Thu Jan",
"jhondoe":"Jhon doe",
"enterthepasswordforsecureyouraccount":"Sisestage parool turvaline \n your konto.",
"entertheemailaddressassociatedwithyouraccount":"Sisestage oma kontoga seotud e-posti aadress.",
"backto":"Tagasi",
"register":"Registreeri",
"leaseenteravalidfirstname":"Liising Sisestage kehtiv eesnimi",
"pleaseenteravalidlastname":"Sisestage kehtiv perekonnanimi",
"pleaseenteravalidemailaddress":"Palun sisesta kehtiv e-posti aadress",
"pleaseenteravalidphoneno":"Palun sisestage kehtiv telefoninumber",
"pleaseselectdate":"Palun valige kuupäev",
"restaurant":"Restoran",
"onesingleroomx2nights":"Üks tuba x 2 ööd",
"menu":"menüü",
"favorite":"Lemmik",
"seeall":"Vaata kõiki",
"pleaseenteravalidusername":"Palun sisestage kehtiv kasutajanimi",
"pleaseenteradateofbirth":"Palun sisestage sünniaeg",
"pleaseentervalidmobilenumber":"Palun sisestage kehtiv mobiiltelefoni number",
"myprofile":"Minu profiil",
"views":"Vaated",
"selectyourpreferredlanguage":"Valige oma eelistatud keel",
"confirmlanguage":"Kinnitage keel",
"termsandcondition":"Tingimused ja seisund",
"privacypolicy":"Privaatsuspoliitika",
};
