final Map<String, String> fiTranslation = {
  "hotelbooking":"Hotellivaraus",
"skip":"Ohita",
"selectdestination":"Valitse kohde ...",
"next":"Seuraava",
"pickupyourtime":"Poimia aikaa ...",
"enjoyyourtrip":"Nauti matkasi...",
"start":"alkaa",
"welcome":" Tervetuloa",
"haveaaccountsignin":"Onko sinulla tili? Kirjaudu sisään",
"login":"Kirjaudu sisään",
"signup":"Kirjaudu",
"password":"Salasana",
"forgotpassword":"Unohtuiko salasana?",
"or":"Tai",
"donthaveanaccount":"Eikö sinulla ole tiliä?",
"username":"Käyttäjänimi",
"mobilenumber":"Matkapuhelinnumero",
"alreadyhaveanaccount":"Onko sinulla jo tili?",
"send":"lähettää",
"backtologin":"Takaisin sisäänkirjautumiseen",
"verifyyouremail":"Vahvista sähköpostisi",
"checkyourmail":"Tarkista postisi",
"wehavesentaotptoyourmailpleaseverify":"Olemme lähettäneet OTP: n sähköpostisi \n Please tarkistaa",
"verify":"Tarkistaa",
"createnewpassword":"Luo uusi salasana",
"newpassword":"uusi salasana",
"conformpassword":"Vastaa salasanaa",
"save":"Tallentaa",
"choosethelanguage":"Valitse kieli",
"english":"Englanti",
"french":"Ranskan kieli",
"gujarati":"Gujarati",
"germany":"Saksa",
"italian":"italialainen",
"belize":"Belize",
"polish":"Kiillottaa",
"brazil":"Brasilia",
"hithomas":"Hei Thomas,",
"findyourhotel":"Etsi hotelli",
"trysingapore":"Kokeile Singapore",
"nearyou":"Lähellä sinua",
"singapore":"Singapore",
"turkey":"Turkki",
"amsterdam":"Amsterdam",
"discover":"Löytää",
"viweall":"Viwe kaikki",
"visited":"Vieraili",
"india":"Intia",
"grandhyatt":"Grand Hyatt",
"onmap":"Kartalla",
"centralareasingapore":"Keskusalue, Singapore",
"carltoncityhotel":"Carlton City Hotel",
"km":"km",
"night":"Yö",
"roomavailable":"Huone",
"details":"Yksityiskohdat",
"sheratonhotel":"Sheraton Hotel",
"maubstreetchicagoil":"Maub Street, Chicago, IL",
"pernight":"per yö",
"review":"Arvostelu",
"facilities":"Tilat",
"wifi":"WiFi",
"gym":"kuntosali",
"pool":"Uima-allas",
"restourant":"Restaurantti",
"parking":"Pysäköinti",
"itisalongestablishedfactthatareaderwillbeadistractedbythereadablecontentofapagewhenlookingatitslayoutthepointofusingloremofaipsumisthatithasamoreorlessnormalnormaldistributionofletters":"On pitkä vakiintunut seikka, että lukija häiritsee sivun luettava sisältö, kun tarkastelet sen ulkoasua. IPSUM: n loremin käyttö on se, että sillä on enemmän tai vähemmän normaali normaali kirjaintenjako.",
"booknow":"Varaa nyt",
"jademountainhotel":"Jade Mountain Hotel",
"price":"Hinta",
"search":" Hae",
"booking":" Varaus",
"standardsingleroom":"Standard - yhden hengen huone",
"fastname":"Nopea nimi",
"lastname":"Sukunimi",
"email":"Sähköposti",
"phoneno":"Puhelin ei.",
"arrival":"Saapuminen",
"departure":"Lähtö",
"viewdetails":"Tarkemmat tiedot",
"additionalservice":"Lisäpalvelu",
"spa":"Kylpylä",
"payment":"Maksu",
"onesingleroomnights":"Yksi yhden hengen yötä",
"total":"Kaikki yhteensä",
"addnewaddress":"Lisää uusi osoite",
"homelocation":"Kotipaikka",
"prospectsaintjamesbarbadosn/a":"Prospect, Saint James, Barbados N / A",
"selectcard":"Valitse kortti",
"creditcard":"Luottokortti",
"paypal":"Paypal",
"applepay":"Apple maksaa",
"pay":"Maksaa",
"addcreditcard":" Lisää luottokortti",
"cardholdername":"kortinhaltijan nimi",
"stefanjohn":"Stefan John",
"cardnumber":"Kortin numero",
"cvv":"Cvv",
"expirationdate":"Viimeinen käyttöpäivä",
"securitycode":"Turvakoodi",
"done":"Tehty",
"yourcardhasbeenaddedsuccessfully":"Korttisi on lisätty onnistuneesti",
"january":"tammikuu",
"february":"helmikuu",
"checkin":"Ilmoittautua",
"checkout":"Tarkista",
"jan":"Tammi",
"grandcity":"Grand City",
"carltoncity":"Carlton City",
"reviews":"Arvostelut",
"thomashenderson":"Thomas Henderson",
"des":"Des",
"loremipsumdolorsitametconsecteturadipiscingelitleonequeloremettortor":"Lorem Ipsum Dolor Sit Amet, Consectur Adipiscing Elit. Leo Neque Lorem et Tortor.",
"recommended":"Suositella",
"filter":"Suodattaa",
"reset":"Nollata",
"category":"Kategoria",
"all":"Kaikki",
"popular":"Suosittu",
"sale":"Myynti",
"luxury":"Luksus",
"pricerange":"Hintaluokka",
"rating":"Luokitus",
"freewifi":"Ilmainen WiFi",
"parkingarea":"Pysäköintialue",
"breakfirstmenu":"Breakfirst-valikko",
"bedroom":"Makuuhuone",
"showresult":"Näytä tulos",
"notification":"Ilmoitus",
"yourappoinmentisbooked":"Appoinment on varattu",
"min":"min",
"loremipsumissimplydummytextoftheprintingindustry":"Lorem Ipsum on yksinkertaisesti painatusteollisuuden teksti.",
"hour":"Tunnin",
"hrs":"HRS",
"day":"Päivä",
"chooseroom":"Valitse huone",
"freecoffee":"Ilmainen kahvi",
"freebreakfast":"Ilmainen aamiainen",
"roseroom":"Rose-huone",
"ndfloor":"lattia",
"loremipsumdolorsitametconsecteturadipiscingelitmuspurusdictumarcutinciduntsitetiamegetquammattisleomaurisdignissimturpisnibhatfeugiatblanditcursusfermentumultriciesnecnislnasceturturpisfacilisisodalesvariuslacuserosetiamturpisipsumvitaedonec":"Lorem Ipsum Dolor Sit Amet, Consectur Adipiscing Elit. Mus Purus Dictum Arcutincidunt Sit etIm Eget Quam. Mattis Leo Mauris, Dignissim Turpis Nibh. FeuGiat Blandit Cursus Fermentum Ultrisies NEC NISL. Nascetur turpis facilisi sodales varius lacus.Eros Etiam turpis ipsum vitae Donec.",
"howlong":"Kuinka kauan",
"addreview":"Lisää arvostelu",
"giveyourgrades":"Anna arvosanat",
"whatdoyousay":"Mitä sanot ?",
"whatdoyouthink":"Mitä mieltä sinä olet ?",
"notrecommended":"Ei suositeltu",
"settings":"asetukset",
"basic":"Perus-",
"account":"Tili",
"privacy&security":"Yksityisyys ja turvallisuus",
"location":"Sijainti",
"darkmode":"Tumma tila",
"more":"Lisää",
"language":"Kieli",
"terms&condition":"Käyttöehdot",
"customerservice":"Asiakaspalvelu",
"signout":"Kirjaudu ulos",
"aboutus":"Meistä",
"contactinformation":"Yhteystiedot",
"companyaddress":"yritys osoite",
"ithassurvivednotonlyfivecenturiesbutalsotheleapintoelectronictypesettingremainingessentiallyunchangeditwaspopularisedinthe1960swiththereleaseofletrasetsheetscontainingloremipsumpassagesandmorerecentlywithdesktoppublishingsoftwarelikealduspagemakerincludingversionsofloremipsum":"Se on selviytynyt paitsi viisi vuosisataa, mutta myös harppaus sähköiseen lajikkeeseen, jäljellä olennaisesti ennallaan. Se oli suosittu 1960-luvulla Lorem Ipsum Passageista sisältävien Lorem Ipsum -kanavien kanssa ja viime aikoina Desktop Publishing -ohjelmistolla, kuten Aldus PageMaker, mukaan lukien Lorem Ipsumin versiot.",
"2privacypolicy":"2. Tietosuojakäytäntö",
"utenimadminimaveniamquisnostrumexercitationnemullamcorporissuscipitlaboriosamnisiutaliquidexeacommodiconsequaturquisautemveleumiurereprehenderitquiineavoluptatevelitessequamnihilmolestiaeconsequaturvelillumquidoloremeumfugiatquovoluptasnullapariatur":"Ut enim ad minima veniam, quis nostrum exercitationnem ullam corpis suscipit labiosam, Nisi Ut Aliquidex EA Commodi seurata? Quis Autem Vel Eum IureReRehenderit Qui EA Vila Velit Esse Quam Nihil Molestiae Bulesaktori, Vel Illum Qui Dolorem Eum Fugiat quo Voluptas Nulla Pariatur?",
"iagreewiththetermsandcondiition":"Olen samaa mieltä ehtojen ja samanaikaisesti",
"iagreewiththeprivacypolicy":"Olen samaa mieltä tietosuojakäytännön kanssa",
"accept":"Hyväksyä",
"decline":"Lasku",
"favourite":"Suosikki",
"thegreathyatt":"Suuri hytt",
"marinabaysingapore":"Marina Bay, Singapore",
"paymentcompleted":"Maksu päättynyt",
"history":"Historia",
"ritzcarlton":"Ritz-Carlton",
"bandaseaindoneshia":"Banda Sea, Indoneshia",
"bookagain":"Kirja uudelleen",
"support&faqs":"Tuki ja usein kysytyt kysymykset",
"hellohowcanwehelpyou":"Hei! kuinka voimme auttaa sinua?",
"presstheheartbuttontoaddanhotel":"Lisää hotelli painamalla Heart-painiketta.",
"paymentsanddiscountfees":"Maksut ja alennusmaksut",
"totamremaperiam":" Totam REM Aperiam",
"sedquiaconsequunturmagni":" SED QUIA CONSUCKUNT MAGNI",
"nequeporroquisquamest":"Neque Porro Quisquam Est",
"aliquamquaeratvoluptatem":"AliquAM Quaerat VolupTeemi",
"bookinginformation":"Varaustiedot",
"profile":"Profiili",
"johnblake":" John Blake",
"editprofile":"Muokkaa profiilia",
"basicdetail":"Perustiedot",
"name":"Nimi",
"dateofbirth":"Syntymäaika",
"phonenumber":"Puhelinnumero",
"male":"Uros",
"female":"Nainen",
"filters":"Suodattimet",
"ridehistory":"Ratsastaa historiaa",
"help":"auta",
"logout":"Kirjautua ulos",
"favoriteplaceinthearea":"Suosikkipaikka alueella",
"reviewdetail":"Tarkista yksityiskohta",
"wedjan":"Ke Jan",
"thujan":"Thu Jan",
"jhondoe":"Jhon doe",
"enterthepasswordforsecureyouraccount":"Syötä salasana turvallisen \n yourin tilille.",
"entertheemailaddressassociatedwithyouraccount":"Anna tilillesi liittyvä sähköpostiosoite.",
"backto":"Takaisin",
"register":"Rekisteri",
"leaseenteravalidfirstname":"vuokrasopimus Anna kelvollinen etunimi",
"pleaseenteravalidlastname":"Anna kelvollinen sukunimi",
"pleaseenteravalidemailaddress":"Ole hyvä ja syötä toimiva sähköpostiosoite",
"pleaseenteravalidphoneno":"Anna kelvollinen puhelin numero",
"pleaseselectdate":"Valitse päivämäärä",
"restaurant":"Ravintola",
"onesingleroomx2nights":"Yksi yhden hengen huone x 2 yötä",
"menu":"valikko",
"favorite":"Suosikki",
"seeall":"Näytä kaikki",
"pleaseenteravalidusername":"Anna kelvollinen käyttäjätunnus",
"pleaseenteradateofbirth":"Anna syntymäaika",
"pleaseentervalidmobilenumber":"Anna kelvollinen matkapuhelinnumero",
"myprofile":"Profiilini",
"views":"Näkymät",
"selectyourpreferredlanguage":"Valitse haluamasi kieli",
"confirmlanguage":"Vahvista kieli",
"termsandcondition":"Käyttöehdot",
"privacypolicy":"Tietosuojakäytäntö",
};
