final Map<String, String> frTranslation = {
  "message":"Message",
"hotelbooking":"Réservation d'hotel",
"skip":"Sauter",
"selectdestination":"Sélectionner la destination...",
"next":"Suivant",
"pickupyourtime":"Ramassez votre temps ...",
"enjoyyourtrip":"Profitez de votre voyage ...",
"start":"Démarrer",
"welcome":" Bienvenue",
"haveaaccountsignin":"Avoir un compte? S'identifier",
"login":"Connexion",
"signup":"S'inscrire",
"password":"Mot de passe",
"forgotpassword":"Mot de passe oublié?",
"or":"Ou",
"donthaveanaccount":"Vous n'avez pas de compte?",
"username":"Nom d'utilisateur",
"mobilenumber":"Numéro de portable",
"alreadyhaveanaccount":"Vous avez déjà un compte?",
"send":"envoyer",
"backtologin":"Retour connexion",
"verifyyouremail":"Vérifiez votre e-mail",
"checkyourmail":"Vérifier votre courrier",
"wehavesentaotptoyourmailpleaseverify":"Nous avons envoyé un OTP à votre courrier \n Vlease vérifier",
"verify":"Vérifier",
"createnewpassword":"Créer un nouveau mot de passe",
"newpassword":"nouveau mot de passe",
"conformpassword":"Mot de passe conforme",
"save":"sauvegarder",
"choosethelanguage":"Choisissez la langue",
"english":"Anglais",
"french":"français",
"gujarati":"Gujarati",
"germany":"Allemagne",
"italian":"italien",
"belize":"Belize",
"polish":"polonais",
"brazil":"Brésil",
"hithomas":"Salut Thomas,",
"findyourhotel":"Trouvez votre hôtel",
"trysingapore":"Essayez Singapour",
"nearyou":"Près de toi",
"singapore":"Singapour",
"turkey":"Turquie",
"amsterdam":"Amsterdam",
"discover":"Découvrir",
"viweall":"Viwe tous",
"visited":"A visité",
"india":"Inde",
"grandhyatt":"Grand Hyatt",
"onmap":"Sur la carte",
"centralareasingapore":"Zone centrale, Singapour",
"carltoncityhotel":"Carlton City Hotel",
"km":"km",
"night":"Nuit",
"roomavailable":"Chambre disponible",
"details":"Des détails",
"sheratonhotel":"Sheraton Hotel",
"maubstreetchicagoil":"Maulu Street, Chicago, Il",
"pernight":"par nuit",
"review":"La revue",
"facilities":"Installations",
"wifi":"Wifi",
"gym":"Gym",
"pool":"Piscine",
"restourant":"Restement",
"parking":"Parking",
"itisalongestablishedfactthatareaderwillbeadistractedbythereadablecontentofapagewhenlookingatitslayoutthepointofusingloremofaipsumisthatithasamoreorlessnormalnormaldistributionofletters":"C'est un fait établi depuis longtemps qu'un lecteur sera distrait par le contenu lisible d'une page lorsqu'il examine sa mise en page. Le point d'utiliser Lorem d'un ipsum est qu'il a une distribution normale de lettres normale plus ou moins normale.",
"booknow":"Reserve maintenant",
"jademountainhotel":"Jade Mountain Hotel",
"price":"Prix",
"search":" Rechercher",
"booking":" Réservation",
"standardsingleroom":"Chambre Simple Standard",
"fastname":"Nom rapide",
"lastname":"Nom de famille",
"email":"E-mail",
"phoneno":"Pas de téléphone.",
"arrival":"Arrivée",
"departure":"Départ",
"viewdetails":"Voir les détails",
"additionalservice":"Service additionnel",
"spa":"Spa",
"payment":"Paiement",
"onesingleroomnights":"Une seule chambre de chambre",
"total":"Total",
"addnewaddress":"Ajouter une nouvelle adresse",
"homelocation":"Localisation de la maison",
"prospectsaintjamesbarbadosn/a":"Perspective, Saint James, Barbade N / A",
"selectcard":"Sélectionner la carte",
"creditcard":"Carte de crédit",
"paypal":"Pay Pal",
"applepay":"Pomme",
"pay":"Payer",
"addcreditcard":" Ajouter une carte de crédit",
"cardholdername":"Nom du titulaire",
"stefanjohn":"Stefan John",
"cardnumber":"Numéro de carte",
"cvv":"Cvv",
"expirationdate":"Date d'expiration",
"securitycode":"Code de sécurité",
"done":"Terminé",
"yourcardhasbeenaddedsuccessfully":"Votre carte a été ajoutée avec succès",
"january":"janvier",
"february":"février",
"checkin":"Enregistrement",
"checkout":"Vérifier",
"jan":"Jan",
"grandcity":"Grande ville",
"carltoncity":"Carlton City",
"reviews":"Commentaires",
"thomashenderson":"Thomas Henderson",
"des":"Des",
"loremipsumdolorsitametconsecteturadipiscingelitleonequeloremettortor":"Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Elit. Leo Neque Lorem et Tortuner.",
"recommended":"conseillé",
"filter":"Filtre",
"reset":"Réinitialiser",
"category":"Catégorie",
"all":"Tous",
"popular":"Populaire",
"sale":"Vente",
"luxury":"Luxe",
"pricerange":"Échelle des prix",
"rating":"Notation",
"freewifi":"Wifi gratuit",
"parkingarea":"Aire de stationnement",
"breakfirstmenu":"Menu Breakfirst",
"bedroom":"Chambre à coucher",
"showresult":"Afficher le résultat",
"notification":"Notification",
"yourappoinmentisbooked":"Votre appartement est réservé",
"min":"min",
"loremipsumissimplydummytextoftheprintingindustry":"Lorem Ipsum est simplement un texte factice de l'industrie de l'impression.",
"hour":"Heure",
"hrs":"HRS",
"day":"Jour",
"chooseroom":"Choisir une chambre",
"freecoffee":"Café libre",
"freebreakfast":"Petit déjeuner gratuit",
"roseroom":"Salle de rose",
"ndfloor":"ND au sol",
"loremipsumdolorsitametconsecteturadipiscingelitmuspurusdictumarcutinciduntsitetiamegetquammattisleomaurisdignissimturpisnibhatfeugiatblanditcursusfermentumultriciesnecnislnasceturturpisfacilisisodalesvariuslacuserosetiamturpisipsumvitaedonec":"Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Elit. Mus Purus Dictum Arcutunidunt Sit etiiam Eget Quam. Mattis Leo Mauris, Dignissim Turpis Nibh. Au Feugiat Blandit Cursus Fermentum Ulticly Nec Nisl. Nasquetur Turpis Facilisi Sodales Varius Lacus.eros etiiam Turpis Ipsum Vitae Donec.",
"howlong":"Combien de temps",
"addreview":"Ajouter un commentaire",
"giveyourgrades":"Donnez vos notes",
"whatdoyousay":"Que dis-tu ?",
"whatdoyouthink":"Qu'est-ce que tu penses ?",
"notrecommended":"Non recommandé",
"settings":"Réglages",
"basic":"De base",
"account":"Compte",
"privacy&security":"Confidentialité et sécurité",
"location":"Lieu",
"darkmode":"Mode sombre",
"more":"Suite",
"language":"Langue",
"terms&condition":"Termes et conditions",
"customerservice":"Service Clients",
"signout":"Se déconnecter",
"aboutus":"À propos de nous",
"contactinformation":"Informations de contact",
"companyaddress":"Adresse de la société",
"ithassurvivednotonlyfivecenturiesbutalsotheleapintoelectronictypesettingremainingessentiallyunchangeditwaspopularisedinthe1960swiththereleaseofletrasetsheetscontainingloremipsumpassagesandmorerecentlywithdesktoppublishingsoftwarelikealduspagemakerincludingversionsofloremipsum":"Il a survécu non seulement cinq siècles, mais également le saut en composition électronique, restant essentiellement inchangé. Il a été popularisé dans les années 1960 avec la libération de feuilles LateSet contenant des passages de Lorem Ipsum, et plus récemment avec des logiciels de publication de bureau tels que Aldus Pagemaker, y compris des versions de Lorem Ipsum.",
"2privacypolicy":"2. Politique de confidentialité",
"utenimadminimaveniamquisnostrumexercitationnemullamcorporissuscipitlaboriosamnisiutaliquidexeacommodiconsequaturquisautemveleumiurereprehenderitquiineavoluptatevelitessequamnihilmolestiaeconsequaturvelillumquidoloremeumfugiatquovoluptasnullapariatur":"UT ENIM ADVIMA VENIAM, QUIS NOSTROM ORDRIVATIONNEM ULLAM CORPORIS SUSCIPIT LACOULIOSAM, NISI UT ALQULIDEX EA COMMODI Carotur? QUI AUTEM VEL EUM EUM IUREREREPREHENDENTE QUI EN EA VOLUGAT VELIT ESSE QUAM NIHIL MOLESTIAE Conséquence, Vel Illum Qui Dolorem Eum Fugiat Quo Voluptas Nulla Pariatur?",
"iagreewiththetermsandcondiition":"Je suis d'accord avec les termes et la conditionnement",
"iagreewiththeprivacypolicy":"Je suis d'accord avec la politique de confidentialité",
"accept":"J'accepte",
"decline":"Déclin",
"favourite":"Favori",
"thegreathyatt":"Le grand hyatt",
"marinabaysingapore":"Marina Bay, Singapour",
"paymentcompleted":"Paiement terminé",
"history":"Histoire",
"ritzcarlton":"Hôtel Ritz Carlton",
"bandaseaindoneshia":"Banda Sea, Indoneshia",
"bookagain":"Réserver",
"support&faqs":"Soutien et FAQ",
"hellohowcanwehelpyou":"Bonjour! Comment pouvons-nous vous aider?",
"presstheheartbuttontoaddanhotel":"Appuyez sur le bouton de coeur pour ajouter un hôtel.",
"paymentsanddiscountfees":"Paiements et frais d'escompte",
"totamremaperiam":" Totam Rem Aperiam",
"sedquiaconsequunturmagni":" SED QUIA EN CORRECTURE MAGNI",
"nequeporroquisquamest":"Neque Porro Quisquam Est",
"aliquamquaeratvoluptatem":"Aliquam Quaerat Voluptatem",
"bookinginformation":"Informations de réservation",
"profile":"Profil",
"johnblake":" John Blake",
"editprofile":"Editer le profil",
"basicdetail":"Détail de base",
"name":"Nom",
"dateofbirth":"Date de naissance",
"phonenumber":"Numéro de téléphone",
"male":"Homme",
"female":"Femme",
"filters":"Filtres",
"ridehistory":"Histoire de promenade",
"help":"Aider",
"logout":"Se déconnecter",
"favoriteplaceinthearea":"Endroit préféré dans la zone",
"reviewdetail":"Détail de l'examen",
"wedjan":"Merci",
"thujan":"Jan Jan",
"jhondoe":"Jhon Doe",
"enterthepasswordforsecureyouraccount":"Entrez le mot de passe du compte Secure \n your.",
"entertheemailaddressassociatedwithyouraccount":"Entrez l'adresse e-mail associée à votre compte.",
"backto":"Retour à",
"register":"S'inscrire",
"leaseenteravalidfirstname":"bail entrer un prénom valide",
"pleaseenteravalidlastname":"Merci d'entrer un nom de famille valide",
"pleaseenteravalidemailaddress":"S'il vous plaît, mettez une adresse email valide",
"pleaseenteravalidphoneno":"S'il vous plaît entrer un numéro de téléphone valide",
"pleaseselectdate":"S'il vous plaît sélectionner la date",
"restaurant":"Restaurant",
"onesingleroomx2nights":"Une chambre simple x 2 nuits",
"menu":"menu",
"favorite":"Favori",
"seeall":"Voir tout",
"pleaseenteravalidusername":"Merci d'entrer un nom d'utilisateur valide",
"pleaseenteradateofbirth":"S'il vous plaît entrer une date de naissance",
"pleaseentervalidmobilenumber":"S'il vous plaît entrer le numéro de mobile valide",
"myprofile":"Mon profil",
"views":"Vues",
"selectyourpreferredlanguage":"Sélectionnez votre langue préférée",
"confirmlanguage":"Confirmer la langue",
"termsandcondition":"Termes et conditions",
"privacypolicy":"Politique de confidentialité",
};
