final Map<String, String> guTranslation = {
  "hotelbooking": "હોટેલ બુકિંગ",
  "skip": "અવગણો",
  "selectdestination": "લક્ષ્ય પસંદ કરો ...",
  "next": "આગળ",
  "pickupyourtime": "તમારો સમય ચૂંટો ...",
  "enjoyyourtrip": "તમારી મુસાફરીનો આનંદ માણો ...",
  "start": "શરૂઆત",
  "welcome": " સ્વાગત",
  "haveaaccountsignin": "એક એકાઉન્ટ છે? સાઇન ઇન કરો",
  "login": "પ્રવેશ કરો",
  "signup": "સાઇન અપ કરો",
  "password": "પાસવર્ડ",
  "forgotpassword": "પાસવર્ડ ભૂલી ગયા છો?",
  "or": "અથવા",
  "donthaveanaccount": "ખાતું નથી?",
  "username": "વપરાશકર્તા નામ",
  "mobilenumber": "મોબાઇલ નંબર",
  "alreadyhaveanaccount": "પહેલેથી જ એક એકાઉન્ટ છે?",
  "send": "મોકલવું",
  "backtologin": "લૉગિન પર પાછા",
  "verifyyouremail": "તમારા ઇમેઇલને ચકાસો",
  "checkyourmail": "તમારી મેઇલ તપાસો",
  "wehavesentaotptoyourmailpleaseverify":
      "અમે તમારા મેઇલ પર OTP મોકલ્યું છે કૃપા કરીને ચકાસો",
  "verify": "ચકાસો",
  "createnewpassword": "નવો પાસવર્ડ બનાવો",
  "newpassword": "નવો પાસવર્ડ",
  "conformpassword": "પાસવર્ડ સાથે સુસંગત",
  "save": "સાચવવું",
  "choosethelanguage": "ભાષા પસંદ કરો",
  "english": "અંગ્રેજી",
  "french": "ફ્રેન્ચ",
  "gujarati": "ગુજરાતી",
  "germany": "જર્મની",
  "italian": "ઇટાલીયન",
  "belize": "બેલીઝ",
  "polish": "પોલિશ",
  "brazil": "બ્રાઝિલ",
  "hithomas": "હાય થોમસ,",
  "findyourhotel": "તમારા હોટેલ શોધો",
  "trysingapore": "સિંગાપુરનો પ્રયાસ કરો",
  "nearyou": "તમારા નજીક",
  "singapore": "સિંગાપોર",
  "turkey": "ટર્કી",
  "amsterdam": "એમ્સ્ટરડેમ",
  "discover": "શોધવું",
  "viweall": "બધા viwe",
  "visited": "મુલાકાત લીધી",
  "india": "ભારત",
  "grandhyatt": "ભવ્ય હાયટ",
  "onmap": "નકશા પર",
  "centralareasingapore": "મધ્ય વિસ્તાર, સિંગાપુર",
  "carltoncityhotel": "કાર્લટન સિટી હોટેલ",
  "km": "કિ.મી.",
  "night": "નાઇટ",
  "roomavailable": "રૂમ ઉપલબ્ધ છે",
  "details": "વિગતો",
  "sheratonhotel": "શેરેટોન હોટેલ",
  "maubstreetchicagoil": "માબ સ્ટ્રીટ, શિકાગો, આઇએલ",
  "pernight": "દરરોજ",
  "review": "સમીક્ષા",
  "facilities": "સુવિધાઓ",
  "wifi": "વાઇફાઇ",
  "gym": "જિમ",
  "pool": "પૂલ",
  "restourant": "પુનઃસ્થાપન કરનાર",
  "parking": "પાર્કિંગ",
  "itisalongestablishedfactthatareaderwillbeadistractedbythereadablecontentofapagewhenlookingatitslayoutthepointofusingloremofaipsumisthatithasamoreorlessnormalnormaldistributionofletters":
      "તે એક લાંબી સ્થાપિત હકીકત છે કે જ્યારે રીડર તેના લેઆઉટ તરફ જોતા પૃષ્ઠની વાંચનીય સામગ્રી દ્વારા વિચલિત થશે. ઇપ્સમના લોરેમનો ઉપયોગ કરવાનો મુદ્દો એ છે કે તેમાં અક્ષરોની વધુ અથવા ઓછી સામાન્ય સામાન્ય વિતરણ છે.",
  "booknow": "હવે બુક કરો",
  "jademountainhotel": "જેડ માઉન્ટેન હોટેલ",
  "price": "કિંમત",
  "search": " શોધ",
  "booking": " બુકિંગ",
  "standardsingleroom": "માનક એકલ રૂમ",
  "fastname": "ઝડપી નામ",
  "lastname": "છેલ્લું નામ",
  "email": "ઇમેઇલ",
  "phoneno": "ફોન નંબર",
  "arrival": "આગમન",
  "departure": "પ્રસ્થાન",
  "viewdetails": "વિગતો જુઓ",
  "additionalservice": "વધારાની સેવા",
  "spa": "સ્પા",
  "payment": "ચુકવણી",
  "onesingleroomnights": "એક સિંગલ રૂમ નાઇટ્સ",
  "total": "કુલ",
  "addnewaddress": "નવું સરનામું ઉમેરો",
  "homelocation": "ઘર સ્થાન",
  "prospectsaintjamesbarbadosn/a": "પ્રોસ્પેક્ટ, સેંટ જેમ્સ, બાર્બાડોસ એન / એ",
  "selectcard": "કાર્ડ પસંદ કરો",
  "creditcard": "ક્રેડીટ કાર્ડ",
  "paypal": "પેપાલ",
  "applepay": "એપલ પગાર",
  "pay": "પગાર",
  "addcreditcard": " ક્રેડિટ કાર્ડ ઉમેરો",
  "cardholdername": "કાર્ડ ધારક નું નામ",
  "stefanjohn": "સ્ટેફન જ્હોન",
  "cardnumber": "કાર્ડ ક્રમાંક",
  "cvv": "સીવીવી",
  "expirationdate": "સમાપ્તિ તારીખ",
  "securitycode": "સુરક્ષા કોડ",
  "done": "પૂર્ણ",
  "yourcardhasbeenaddedsuccessfully":
      "તમારું કાર્ડ સફળતાપૂર્વક ઉમેરવામાં આવ્યું છે",
  "january": "જાન્યુઆરી",
  "february": "ફેબ્રુઆરી",
  "checkin": "માં ચેક ઇન",
  "checkout": "તપાસ કરવી",
  "jan": "જાન્યુઆરી",
  "grandcity": "ગ્રાન્ડ સિટી",
  "carltoncity": "કાર્લટન સિટી",
  "reviews": "સમીક્ષાઓ",
  "thomashenderson": "થોમસ હેન્ડરસન",
  "des": "ઊન",
  "loremipsumdolorsitametconsecteturadipiscingelitleonequeloremettortor":
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. લીઓ નેક લોરેમ અને ટોર્ટર.",
  "recommended": "ભલામણ",
  "filter": "ફિલ્ટર",
  "reset": "ફરીથી સેટ કરવું",
  "category": "વર્ગ",
  "all": "બધા",
  "popular": "પ્રખ્યાત",
  "sale": "વેચાણ",
  "luxury": "વૈભવી",
  "pricerange": "ભાવ રેંજ",
  "rating": "રેટિંગ",
  "freewifi": "મફત વાઇફાઇ",
  "parkingarea": "પાર્કિંગ વિસ્તાર",
  "breakfirstmenu": "બ્રેકફાયર મેનુ",
  "bedroom": "બેડરૂમ",
  "showresult": "પરિણામ બતાવો",
  "notification": "સૂચના",
  "yourappoinmentisbooked": "તમારા appoinment બુક કરાવે છે",
  "min": "મિન",
  "loremipsumissimplydummytextoftheprintingindustry":
      "લોરેમ ઇપ્સમ ફક્ત પ્રિન્ટિંગ ઉદ્યોગનો ડમી ટેક્સ્ટ છે.",
  "hour": "કલાક",
  "hrs": "એચઆરએસ",
  "day": "દિવસ",
  "chooseroom": "રૂમ પસંદ કરો",
  "freecoffee": "મફત કૉફી",
  "freebreakfast": "મફત નાસ્તો",
  "roseroom": "રોઝ રૂમ",
  "ndfloor": "માળ",
  "loremipsumdolorsitametconsecteturadipiscingelitmuspurusdictumarcutinciduntsitetiamegetquammattisleomaurisdignissimturpisnibhatfeugiatblanditcursusfermentumultriciesnecnislnasceturturpisfacilisisodalesvariuslacuserosetiamturpisipsumvitaedonec":
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mus Purus dictum arcutincidunt બેસીને ઇલિયમ eget quam. Mattis લીઓ મોરિસ, ડિગ્નિસિમ ટર્પીસ નિહ. Fugiat blandit cursus fermentum અલ્ટ્રિસીઝ nec nisl પર. નાસ્કેટુર ટર્પીસ ફેસિલીસી સોડેલ્સ વેરિયસ lacus.eros atiam turpis ipsum vitae ડોનેક.",
  "howlong": "કેટલુ લાંબુ",
  "addreview": "સમીક્ષા ઉમેરો",
  "giveyourgrades": "તમારા ગ્રેડ આપો",
  "whatdoyousay": "તમે શું કહો છો ?",
  "whatdoyouthink": "તમે શું વિચારો છો ?",
  "notrecommended": "આગ્રહણીય નથી",
  "settings": "ગોઠવણીઓ",
  "basic": "પાયાની",
  "account": "હિસાબ",
  "privacy&security": "ગોપનીયતા અને સુરક્ષા",
  "location": "સ્થાન",
  "darkmode": "ડાર્ક મોડ",
  "more": "વધુ",
  "language": "ભાષા",
  "terms&condition": "શરતો અને શરત",
  "customerservice": "ગ્રાહક સેવા",
  "signout": "સાઇન આઉટ",
  "aboutus": "અમારા વિશે",
  "contactinformation": "સંપર્ક માહિતી",
  "companyaddress": "કંપનીનું સરનામું",
  "ithassurvivednotonlyfivecenturiesbutalsotheleapintoelectronictypesettingremainingessentiallyunchangeditwaspopularisedinthe1960swiththereleaseofletrasetsheetscontainingloremipsumpassagesandmorerecentlywithdesktoppublishingsoftwarelikealduspagemakerincludingversionsofloremipsum":
      "તે માત્ર પાંચ સદીઓથી જ અસ્તિત્વમાં નથી, પણ ઇલેક્ટ્રોનિક ટાઇપસેટીંગમાં કૂદકાવે છે, તે આવશ્યક રૂપે અપરિવર્તિત છે. તે 1960 ના દાયકામાં લોકપ્રિયતા શીટ્સની રજૂઆત સાથે લોકપ્રિય છે, જેમાં લોરેસ ઇપ્સમ પેસેજ છે, અને તાજેતરમાં ડેસ્કટૉપ પબ્લિશિંગ સૉફ્ટવેર જેવા કે એલ્ડસ પેજમેકર જેવા કે એલ્ડસ પેજમેકરનો સમાવેશ થાય છે.",
  "privacypolicy": "ગોપનીયતા નીતિ",
  "utenimadminimaveniamquisnostrumexercitationnemullamcorporissuscipitlaboriosamnisiutaliquidexeacommodiconsequaturquisautemveleumiurereprehenderitquiineavoluptatevelitessequamnihilmolestiaeconsequaturvelillumquidoloremeumfugiatquovoluptasnullapariatur":
      "U kinima veniam, Quis nostrum કસરત ullam કોર્પોરેશનો ullam કોર્પોરેશિસમ, eisi etiquidex ઇએ કોમો કોમોડિક પરિણામ? ક્યુસ ઓટીમ વેલ ઇયુઆરઆઇઆરએરેપ્રેન્ડેન્ડેન્ડિટ qui ea ea elauptate velit esse Quam nihil molestiae પરિણામ, vel illum qui dolorem eum fugiat શું Volupts nulla paraturur?",
  "iagreewiththetermsandcondiition": "હું નિયમો અને સંજ્ઞાઓથી સંમત છું",
  "iagreewiththeprivacypolicy": "હું ગોપનીયતા નીતિથી સંમત છું",
  "accept": "સ્વીકારવું",
  "decline": "ઘટાડો",
  "favourite": "મનપસંદ",
  "thegreathyatt": "મહાન હયાત",
  "marinabaysingapore": "મરિના ખાડી, સિંગાપુર",
  "paymentcompleted": "ચુકવણી પૂર્ણ",
  "history": "ઇતિહાસ",
  "ritzcarlton": "રિટ્ઝ-કાર્લટન",
  "bandaseaindoneshia": "બંદા સમુદ્ર, ઇન્ડોનેશિયા",
  "bookagain": "ફરીથી પુસ્તક",
  "support&faqs": "સપોર્ટ અને FAQs",
  "hellohowcanwehelpyou": "નમસ્તે! અમે તમને કેવી રીતે મદદ કરી શકીએ?",
  "presstheheartbuttontoaddanhotel": "હોટેલ ઉમેરવા માટે હાર્ટ બટન દબાવો.",
  "paymentsanddiscountfees": "ચુકવણી અને ડિસ્કાઉન્ટ ફી",
  "totamremaperiam": " ટોટમ રીમ એપરિઅમ",
  "sedquiaconsequunturmagni": " Sed quia પરિણામે મેગ્ની",
  "nequeporroquisquamest": "નેક પોરો ક્વિસ્ક્યુમ એસ્ટ",
  "aliquamquaeratvoluptatem": "Aliquam Quaerat Voluptematem",
  "bookinginformation": "બુકિંગ માહિતી",
  "profile": "રૂપરેખા",
  "johnblake": " જ્હોન બ્લેક",
  "editprofile": "પ્રોફાઇલ સંપાદિત કરો",
  "basicdetail": "મૂળભૂત વિગત",
  "name": "નામ",
  "dateofbirth": "જન્મ તારીખ",
  "phonenumber": "ફોન નંબર",
  "male": "પુરુષ",
  "female": "સ્ત્રી",
  "filters": "ગાળકો",
  "ridehistory": "રાઇડ ઇતિહાસ",
  "help": "મદદ",
  "logout": "લૉગ આઉટ",
  "favoriteplaceinthearea": "વિસ્તારમાં પ્રિય સ્થળ",
  "reviewdetail": "સમીક્ષા વિગતવાર",
  "wedjan": "બુધ જાન્યુ",
  "thujan": "થુ જાન",
  "jhondoe": "Jhon doe",
  "enterthepasswordforsecureyouraccount":
      "સુરક્ષિત તમારું એકાઉન્ટ માટે પાસવર્ડ દાખલ કરો.",
  "entertheemailaddressassociatedwithyouraccount":
      "તમારા એકાઉન્ટ સાથે સંકળાયેલ ઇમેઇલ સરનામું દાખલ કરો.",
  "backto": "પાછળ",
  "register": "રજિસ્ટર કરવું",
  "leaseenteravalidfirstname": "લીઝ માન્ય પ્રથમ નામ દાખલ કરો",
  "pleaseenteravalidlastname": "કૃપા કરીને માન્ય છેલ્લું નામ દાખલ કરો",
  "pleaseenteravalidemailaddress": "કૃપા કરીને માન્ય ઇમેઇલ સરનામું દાખલ કરો",
  "pleaseenteravalidphoneno": "કૃપા કરીને માન્ય ફોન નંબર દાખલ કરો.",
  "pleaseselectdate": "કૃપા કરીને તારીખ પસંદ કરો",
  "restaurant": "રેસ્ટોરન્ટ",
  "onesingleroomx2nights": "એક સિંગલ રૂમ એક્સ 2 રાત",
  "menu": "મેનૂ",
  "favorite": "મનપસંદ",
  "seeall": "બધા જુઓ",
  "pleaseenteravalidusername": "કૃપા કરીને માન્ય વપરાશકર્તા નામ દાખલ કરો",
  "pleaseenteradateofbirth": "કૃપા કરીને જન્મની તારીખ દાખલ કરો",
  "pleaseentervalidmobilenumber": "કૃપા કરીને માન્ય મોબાઇલ નંબર દાખલ કરો",
  "myprofile": "મારી પ્રોફાઈલ",
  "views": "દૃશ્યો",
  "selectyourpreferredlanguage": "તમારી પસંદીદા ભાષા પસંદ કરો",
  "confirmlanguage": "ભાષાની પુષ્ટિ કરો",
  "termsandcondition": "નિયમો અને શરતો",
};
