final Map<String, String> hiTranslation = {
  "hotelbooking": "होटल बुकिंग",
  "skip": "छोड़ें",
  "selectdestination": "गंतव्य का चयन करें ...",
  "next": "अगला",
  "pickupyourtime": "अपना समय उठाओ ...",
  "enjoyyourtrip": "अपनी यात्रा का आनंद लें...",
  "start": "शुरू",
  "welcome": " स्वागत",
  "haveaaccountsignin": "खाता है? साइन इन करें",
  "login": "लॉग इन करें",
  "signup": "साइन अप करें",
  "password": "कुंजिका",
  "forgotpassword": "पासवर्ड भूल गए?",
  "or": "या",
  "donthaveanaccount": "खाता नहीं है?",
  "username": "उपयोगकर्ता नाम",
  "mobilenumber": "मोबाइल नंबर",
  "alreadyhaveanaccount": "पहले से ही एक खाता है?",
  "send": "भेजना",
  "backtologin": "लॉगिन पर वापस जाएं",
  "verifyyouremail": "अपना ई मेल सत्यापित करें",
  "checkyourmail": "अपना मेल देखें",
  "wehavesentaotptoyourmailpleaseverify":
      "हमने आपके मेल पर एक ओटीपी भेजा है \n कृपया सत्यापित करें",
  "verify": "सत्यापित करें",
  "createnewpassword": "नया पासवर्ड बनाएं",
  "newpassword": "नया पासवर्ड",
  "conformpassword": "पासवर्ड",
  "save": "सहेजें",
  "choosethelanguage": "भाषा चुनें",
  "english": "अंग्रेज़ी",
  "french": "फ्रांसीसी",
  "gujarati": "गुजराती",
  "germany": "जर्मनी",
  "italian": "इतालवी",
  "belize": "बेलीज़",
  "polish": "पोलिश",
  "brazil": "ब्राज़िल",
  "hithomas": "हाय थॉमस,",
  "findyourhotel": "अपना होटल खोजें",
  "trysingapore": "सिंगापुर का प्रयास करें",
  "nearyou": "आप के पास",
  "singapore": "सिंगापुर",
  "turkey": "तुर्की",
  "amsterdam": "एम्स्टर्डम",
  "discover": "डिस्कवर",
  "viweall": "Viwe सब",
  "visited": "का दौरा किया",
  "india": "इंडिया",
  "grandhyatt": "ग्रैंड हयात",
  "onmap": "मानचित्र पर",
  "centralareasingapore": "केंद्रीय क्षेत्र, सिंगापुर",
  "carltoncityhotel": "कार्लटन सिटी होटल",
  "km": "किमी",
  "night": "रात",
  "roomavailable": "कमरा खाली है",
  "details": "विवरण",
  "sheratonhotel": "शेरेटन होटल",
  "maubstreetchicagoil": "मॉब स्ट्रीट, शिकागो, आईएल",
  "pernight": "प्रति रात",
  "review": "समीक्षा",
  "facilities": "सुविधाएं",
  "wifi": "Wifi",
  "gym": "जिम",
  "pool": "पूल",
  "restourant": "रेस्टोरांट",
  "parking": "पार्किंग",
  "itisalongestablishedfactthatareaderwillbeadistractedbythereadablecontentofapagewhenlookingatitslayoutthepointofusingloremofaipsumisthatithasamoreorlessnormalnormaldistributionofletters":
      "यह एक लंबे समय से स्थापित तथ्य है कि एक पाठक अपने लेआउट को देखते समय किसी पृष्ठ की पठनीय सामग्री से विचलित होगा। आईपीएसयूएम के लॉरेम का उपयोग करने का बिंदु यह है कि इसमें अक्षरों का अधिक सामान्य सामान्य सामान्य वितरण है।",
  "booknow": "अभी बुक करें",
  "jademountainhotel": "जेड माउंटेन होटल",
  "price": "कीमत",
  "search": " खोज",
  "booking": " बुकिंग",
  "standardsingleroom": "मानक एकल कमरा",
  "fastname": "फास्ट नाम",
  "lastname": "अंतिम नाम",
  "email": "ईमेल",
  "phoneno": "फोन नंबर।",
  "arrival": "पहुचना",
  "departure": "प्रस्थान",
  "viewdetails": "विवरण देखें",
  "additionalservice": "अतिरिक्त सेवा",
  "spa": "स्पा",
  "payment": "भुगतान",
  "onesingleroomnights": "एक सिंगल रूम नाइट्स",
  "total": "संपूर्ण",
  "addnewaddress": "नया पता जोड़ें",
  "homelocation": "गृह स्थान",
  "prospectsaintjamesbarbadosn/a": "प्रॉस्पेक्ट, सेंट जेम्स, बारबाडोस एन / ए",
  "selectcard": "कार्ड का चयन करें",
  "creditcard": "क्रेडिट कार्ड",
  "paypal": "पेपैल",
  "applepay": "मोटी वेतन",
  "pay": "वेतन",
  "addcreditcard": " क्रेडिट कार्ड जोड़ें",
  "cardholdername": "कार्डधारक का नाम",
  "stefanjohn": "स्टीफन जॉन",
  "cardnumber": "कार्ड संख्या",
  "cvv": "सीवीवी",
  "expirationdate": "समाप्ति तिथि",
  "securitycode": "सुरक्षा कोड",
  "done": "पूर्ण",
  "yourcardhasbeenaddedsuccessfully": "आपका कार्ड सफलतापूर्वक जोड़ा गया है",
  "january": "जनवरी",
  "february": "फ़रवरी",
  "checkin": "चेक इन",
  "checkout": "चेक आउट",
  "jan": "जनवरी",
  "grandcity": "ग्रैंड सिटी",
  "carltoncity": "कार्लटन सिटी",
  "reviews": "समीक्षा",
  "thomashenderson": "थॉमस हेंडरसन",
  "des": "डेस",
  "loremipsumdolorsitametconsecteturadipiscingelitleonequeloremettortor":
      "Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Elit। लियो Neque Lorem et tortor।",
  "recommended": "अनुशंसित",
  "filter": "फ़िल्टर",
  "reset": "रीसेट",
  "category": "श्रेणी",
  "all": "सभी",
  "popular": "लोकप्रिय",
  "sale": "बिक्री",
  "luxury": "विलासिता",
  "pricerange": "मूल्य सीमा",
  "rating": "रेटिंग",
  "freewifi": "मुक्त वाईफाई",
  "parkingarea": "पार्किंग क्षेत्र",
  "breakfirstmenu": "ब्रेकफ़र्स्ट मेनू",
  "bedroom": "शयनकक्ष",
  "showresult": "परिणाम दिखाओ",
  "notification": "अधिसूचना",
  "yourappoinmentisbooked": "आपका Appoinment बुक किया गया है",
  "min": "मिनट",
  "loremipsumissimplydummytextoftheprintingindustry":
      "Lorem Ipsum मुद्रण उद्योग का बस डमी पाठ है।",
  "hour": "घंटा",
  "hrs": "घंटे",
  "day": "दिन",
  "chooseroom": "कमरा चुनें",
  "freecoffee": "मुक्त कॉफी",
  "freebreakfast": "मुफ्त नाश्ता",
  "roseroom": "गुलाब का कमरा",
  "ndfloor": "एनडी मंजिल",
  "loremipsumdolorsitametconsecteturadipiscingelitmuspurusdictumarcutinciduntsitetiamegetquammattisleomaurisdignissimturpisnibhatfeugiatblanditcursusfermentumultriciesnecnislnasceturturpisfacilisisodalesvariuslacuserosetiamturpisipsumvitaedonec":
      "Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Elit। Mus Porus Dictum Arcutincidunt बैठो Etiam Eget Quam। मैटिस लियो मॉरीस, डिनीसिम टर्पी निबंध। Feugiat Blandit Cursus Fermentum अल्ट्रिसिस एनईसी NIST में। NASCETUR TURPIS Facilisi Sodales Varius Lacus.eros Etiam Turpis Ipsum Vitae Donec।",
  "howlong": "कितनी देर",
  "addreview": "समीक्षा जोड़ें",
  "giveyourgrades": "अपने ग्रेड दें",
  "whatdoyousay": "क्यों भाई क्या कहते हो ?",
  "whatdoyouthink": "तुम क्या सोचते हो ?",
  "notrecommended": "सिफारिश नहीं की गई",
  "settings": "समायोजन",
  "basic": "बुनियादी",
  "account": "हेतु",
  "privacy&security": "निजता एवं सुरक्षा",
  "location": "स्थान",
  "darkmode": "डार्क मोड",
  "more": "अधिक",
  "language": "भाषा",
  "terms&condition": "नियम व शर्त",
  "customerservice": "ग्राहक सेवा",
  "signout": "साइन आउट",
  "aboutus": "हमारे बारे में",
  "contactinformation": "संपर्क जानकारी",
  "companyaddress": "कंपनी का पता",
  "ithassurvivednotonlyfivecenturiesbutalsotheleapintoelectronictypesettingremainingessentiallyunchangeditwaspopularisedinthe1960swiththereleaseofletrasetsheetscontainingloremipsumpassagesandmorerecentlywithdesktoppublishingsoftwarelikealduspagemakerincludingversionsofloremipsum":
      "यह न केवल पांच शताब्दियों, बल्कि इलेक्ट्रॉनिक टाइपसेटिंग में छलांग भी बच गया है, जो अनिवार्य रूप से अपरिवर्तित शेष है। इसे 1 9 60 के दशक में लोरम आईपीएसयूएम मार्गों वाली लेट्रेट शीट की रिहाई के साथ लोकप्रिय किया गया था, और हाल ही में डेस्कटॉप प्रकाशन सॉफ्टवेयर जैसे एलडीयूएस पेजम निर्माता के साथ लोरम आईपीएसएम के संस्करणों सहित।",
  "2privacypolicy": "2. गोपनीयता नीति",
  "utenimadminimaveniamquisnostrumexercitationnemullamcorporissuscipitlaboriosamnisiutaliquidexeacommodiconsequaturquisautemveleumiurereprehenderitquiineavoluptatevelitessequamnihilmolestiaeconsequaturvelillumquidoloremeumfugiatquovoluptasnullapariatur":
      "यूटी एनिम एडी मिनीमा वेनियम, क्विस नोस्ट्रम व्यायामनाम उलम निगम संसारसिस लेबरियोम, निसी यूटी Aliquidex Ea Commositi परिणाम? Quis Autem Vel Eum IurreePrerependeit Qui in EA Voluptate Velit Esee Quam Nihil Molestiae परिणाम, Vel Illum Qui Dolorem Eum Fugiat Quo Voluptas Nulla Pariatur?",
  "iagreewiththetermsandcondiition": "मैं शर्तों और संवेदना से सहमत हूं",
  "iagreewiththeprivacypolicy": "मैं गोपनीयता नीति से सहमत हूं",
  "accept": "स्वीकार करना",
  "decline": "पतन",
  "favourite": "पसंदीदा",
  "thegreathyatt": "महान हयात",
  "marinabaysingapore": "मरीना बे, सिंगापुर",
  "paymentcompleted": "भुगतान पूरा हुआ",
  "history": "इतिहास",
  "ritzcarlton": "रिट्ज कार्लटन",
  "bandaseaindoneshia": "बांदा सागर, इंडोनेशिया",
  "bookagain": "फिर से बुक करें",
  "support&faqs": "समर्थन और अक्सर पूछे जाने वाले प्रश्न",
  "hellohowcanwehelpyou": "नमस्कार! हम आपकी किस प्रकार मदद कर सकते हैं?",
  "presstheheartbuttontoaddanhotel": "एक होटल जोड़ने के लिए दिल बटन दबाएं।",
  "paymentsanddiscountfees": "भुगतान और छूट शुल्क",
  "totamremaperiam": " टोटाम रेम एपीरियम",
  "sedquiaconsequunturmagni": " एसईडी क्विया परिणाम",
  "nequeporroquisquamest": "Neque Porro Quisquam Est",
  "aliquamquaeratvoluptatem": "Aliquam Quaerat Voluptatem",
  "bookinginformation": "बुकिंग जानकारी",
  "profile": "प्रोफ़ाइल",
  "johnblake": " जॉन ब्लेक",
  "editprofile": "प्रोफ़ाइल संपादित करें",
  "basicdetail": "बुनियादी विवरण",
  "name": "नाम",
  "dateofbirth": "जन्म की तारीख",
  "phonenumber": "फ़ोन नंबर",
  "male": "पुरुष",
  "female": "महिला",
  "filters": "फिल्टर",
  "ridehistory": "सवारी इतिहास",
  "help": "मदद",
  "logout": "लॉग आउट",
  "favoriteplaceinthearea": "क्षेत्र में पसंदीदा जगह",
  "reviewdetail": "समीक्षा विवरण",
  "wedjan": "बुध जन",
  "thujan": "थू जन",
  "jhondoe": "झोन डो",
  "enterthepasswordforsecureyouraccount":
      "सुरक्षित \n आपके खाते के लिए पासवर्ड दर्ज करें।",
  "entertheemailaddressassociatedwithyouraccount":
      "अपने खाते से जुड़े ईमेल पता दर्ज करें।",
  "backto": "वापस",
  "register": "रजिस्टर करें",
  "leaseenteravalidfirstname": "पट्टा एक वैध पहला नाम दर्ज करें",
  "pleaseenteravalidlastname": "कृपया एक वैध अंतिम नाम को दर्ज करें",
  "pleaseenteravalidemailaddress": "कृपया एक वैध ई - मेल एड्रेस डालें",
  "pleaseenteravalidphoneno": "कृपया एक वैध फोन नंबर दर्ज करें",
  "pleaseselectdate": "कृपया तिथि का चयन करें",
  "restaurant": "रेस्टोरेंट",
  "onesingleroomx2nights": "एक सिंगल रूम x 2 रातें",
  "menu": "मेन्यू",
  "favorite": "पसंदीदा",
  "seeall": "सभी देखें",
  "pleaseenteravalidusername": "कृपया एक वैध उपयोगकर्ता नाम दर्ज करें",
  "pleaseenteradateofbirth": "कृपया जन्मतिथि दर्ज करें",
  "pleaseentervalidmobilenumber": "कृपया वैध मोबाइल नंबर दर्ज करें",
  "myprofile": "मेरी प्रोफाइल",
  "views": "विचारों",
  "selectyourpreferredlanguage": "अपनी पसंदीदा भाषा का चयन करें",
  "confirmlanguage": "भाषा की पुष्टि करें",
  "termsandcondition": "नियम व शर्तें",
  "privacypolicy": "गोपनीयता नीति",
};
