final Map<String, String> idTranslation = {
  "hotelbooking":"Pemesanan hotel",
"skip":"Melewati",
"selectdestination":"Pilih tujuan ...",
"next":"Lanjut",
"pickupyourtime":"Ambil waktu Anda ...",
"enjoyyourtrip":"Nikmati perjalananmu...",
"start":"Awal",
"welcome":" Selamat datang",
"haveaaccountsignin":"Punya akun? Masuk",
"login":"Gabung",
"signup":"Mendaftar",
"password":"Kata sandi",
"forgotpassword":"Tidak ingat kata sandi?",
"or":"Atau",
"donthaveanaccount":"Tidak punya akun?",
"username":"Nama belakang",
"mobilenumber":"Nomor handphone",
"alreadyhaveanaccount":"Sudah memiliki akun?",
"send":"mengirim",
"backtologin":"Kembali untuk masuk",
"verifyyouremail":"Verifikasi email Anda",
"checkyourmail":"Periksa email Anda",
"wehavesentaotptoyourmailpleaseverify":"Kami telah mengirim OTP ke email Anda \n Harap verifikasi",
"verify":"Memeriksa",
"createnewpassword":"Buat kata sandi baru",
"newpassword":"kata sandi baru",
"conformpassword":"Mematuhi kata sandi",
"save":"Menyimpan",
"choosethelanguage":"Pilih bahasa",
"english":"bahasa Inggris",
"french":"Perancis",
"gujarati":"Gujarati",
"germany":"Jerman.",
"italian":"Italia",
"belize":"Belize.",
"polish":"Polandia",
"brazil":"Brazil",
"hithomas":"Hai Thomas,",
"findyourhotel":"Temukan hotel Anda",
"trysingapore":"Coba Singapura",
"nearyou":"Di dekat Anda",
"singapore":"Singapura",
"turkey":"Turki",
"amsterdam":"Amsterdam.",
"discover":"Menemukan",
"viweall":"Viwe all.",
"visited":"Dikunjungi",
"india":"India",
"grandhyatt":"Grand Hyatt",
"onmap":"Di peta",
"centralareasingapore":"Area Pusat, Singapura",
"carltoncityhotel":"Carlton City Hotel",
"km":"Km.",
"night":"Malam",
"roomavailable":"Tersedia kamar",
"details":"Detail.",
"sheratonhotel":"Sheraton Hotel.",
"maubstreetchicagoil":"Maub Street, Chicago, IL",
"pernight":"per malam",
"review":"Tinjauan",
"facilities":"Fasilitas",
"wifi":"Wifi",
"gym":"Gym",
"pool":"Kolam",
"restourant":"Restourtant.",
"parking":"Parkir",
"itisalongestablishedfactthatareaderwillbeadistractedbythereadablecontentofapagewhenlookingatitslayoutthepointofusingloremofaipsumisthatithasamoreorlessnormalnormaldistributionofletters":"Ini adalah fakta yang sudah lama mapan bahwa pembaca akan terganggu oleh konten yang dapat dibaca dari suatu halaman ketika melihat tata letaknya. Intinya menggunakan Lorem ipsum adalah memiliki distribusi huruf normal yang lebih atau kurang normal.",
"booknow":"Pesan sekarang",
"jademountainhotel":"Jade Mountain Hotel",
"price":"Harga",
"search":" Mencari",
"booking":" Pemesanan",
"standardsingleroom":"Kamar Single Standar",
"fastname":"Nama cepat.",
"lastname":"Nama keluarga",
"email":"Surel",
"phoneno":"No Telepon.",
"arrival":"Kedatangan",
"departure":"Keberangkatan",
"viewdetails":"Melihat rincian",
"additionalservice":"Layanan tambahan",
"spa":"Spa",
"payment":"Pembayaran",
"onesingleroomnights":"Satu malam kamar single",
"total":"Total",
"addnewaddress":"Tambahkan alamat baru",
"homelocation":"Lokasi rumah",
"prospectsaintjamesbarbadosn/a":"Prospek, Saint James, Barbados N / A",
"selectcard":"Pilih Kartu",
"creditcard":"Kartu kredit",
"paypal":"Paypal.",
"applepay":"Apple Pay.",
"pay":"Membayar",
"addcreditcard":" Tambahkan kartu kredit",
"cardholdername":"tanda pengenal",
"stefanjohn":"Stefan John.",
"cardnumber":"Nomor kartu",
"cvv":"CVV.",
"expirationdate":"Tanggal habis tempo",
"securitycode":"Kode keamanan",
"done":"Selesai",
"yourcardhasbeenaddedsuccessfully":"Kartu Anda berhasil ditambahkan",
"january":"Januari",
"february":"Februari",
"checkin":"Mendaftar",
"checkout":"Periksa",
"jan":"Jan.",
"grandcity":"Grand City.",
"carltoncity":"Carlton City.",
"reviews":"Ulasan",
"thomashenderson":"Thomas Henderson",
"des":"Des.",
"loremipsumdolorsitametconsecteturadipiscingelitleonequeloremettortor":"Lorem Ipsum Dolor Sit Amet, Konsektetur Adipiscing ELIT. Leo Neque Lorem et Tortor.",
"recommended":"Direkomendasikan",
"filter":"Saring",
"reset":"Mengatur ulang",
"category":"Kategori",
"all":"Semua",
"popular":"Populer",
"sale":"Penjualan",
"luxury":"Kemewahan",
"pricerange":"Kisaran harga",
"rating":"Peringkat",
"freewifi":"Wifi gratis",
"parkingarea":"Area parkir",
"breakfirstmenu":"Menu breakfirst.",
"bedroom":"Kamar tidur",
"showresult":"Menunjukkan hasilnya",
"notification":"Pemberitahuan",
"yourappoinmentisbooked":"Appoinment Anda dipesan",
"min":"menit",
"loremipsumissimplydummytextoftheprintingindustry":"Lorem Ipsum hanyalah teks dummy dari industri percetakan.",
"hour":"Jam",
"hrs":"Jam",
"day":"Hari",
"chooseroom":"Pilih Ruang",
"freecoffee":"Kopi gratis",
"freebreakfast":"Sarapan gratis",
"roseroom":"Rose Room.",
"ndfloor":"lantai nd.",
"loremipsumdolorsitametconsecteturadipiscingelitmuspurusdictumarcutinciduntsitetiamegetquammattisleomaurisdignissimturpisnibhatfeugiatblanditcursusfermentumultriciesnecnislnasceturturpisfacilisisodalesvariuslacuserosetiamturpisipsumvitaedonec":"Lorem Ipsum Dolor Sit Amet, Konsektetur Adipiscing ELIT. Mus Purus Dictum Arcutincidunt duduk etiam Eget Quam. Mattis Leo Mauris, Dignissim Turpis Nibh. Di Feugiat Blandit Cursus Ultricies Fermentum NEC NISL. Nascetur Turpis Facilisi Sodales Varius Lacus.eros Etiam Turpis Ipsum Vitae Donec.",
"howlong":"Berapa lama",
"addreview":"Tambahkan ulasan",
"giveyourgrades":"Berikan nilai Anda",
"whatdoyousay":"Apa yang kamu katakan ?",
"whatdoyouthink":"Bagaimana menurutmu ?",
"notrecommended":"Tidak direkomendasikan",
"settings":"Pengaturan",
"basic":"Dasar",
"account":"Akun",
"privacy&security":"Privasi & Keamanan",
"location":"Lokasi",
"darkmode":"Mode gelap.",
"more":"Lagi",
"language":"Bahasa",
"terms&condition":"Syarat & Ketentuan",
"customerservice":"Pelayanan pelanggan",
"signout":"Keluar",
"aboutus":"Tentang kami",
"contactinformation":"Kontak informasi",
"companyaddress":"Alamat perusahaan",
"ithassurvivednotonlyfivecenturiesbutalsotheleapintoelectronictypesettingremainingessentiallyunchangeditwaspopularisedinthe1960swiththereleaseofletrasetsheetscontainingloremipsumpassagesandmorerecentlywithdesktoppublishingsoftwarelikealduspagemakerincludingversionsofloremipsum":"Itu telah bertahan tidak hanya lima abad, tetapi juga lompatan ke jenis elektronik, tetap pada dasarnya tidak berubah. Itu dipopulerkan pada 1960-an dengan rilis lembaran letraset yang mengandung lorong IPSUM LOREM, dan baru-baru ini dengan perangkat lunak penerbitan desktop seperti Aldus PageMaker termasuk versi Lorem Ipsum.",
"privacypolicy":"Kebijakan pribadi",
"utenimadminimaveniamquisnostrumexercitationnemullamcorporissuscipitlaboriosamnisiutaliquidexeacommodiconsequaturquisautemveleumiurereprehenderitquiineavoluptatevelitessequamnihilmolestiaeconsequaturvelillumquidoloremeumfugiatquovoluptasnullapariatur":"UT Enim Ad Minimal Veniam, Quis Nostrum ExeangnemNem Ullam Corporis Suscipit Laboriosam, Nisi UT Aliquidex EA Commodi Konsekuonatur? Quis Autem Vel Eum Iureseprehendit Qui di EA Voluptate Velit Esse Quam Nihil Molestiae, Vel Illum Qui Dolorem Eum Fugatta Nulla Pariatur?",
"iagreewiththetermsandcondiition":"Saya setuju dengan persyaratan dan condition",
"iagreewiththeprivacypolicy":"Saya setuju dengan Kebijakan Privasi",
"accept":"Menerima",
"decline":"Menolak",
"favourite":"Favorit",
"thegreathyatt":"Hyatt yang hebat.",
"marinabaysingapore":"Marina Bay, Singapura",
"paymentcompleted":"Pembayaran selesai",
"history":"Sejarah",
"ritzcarlton":"Ritz Carlton",
"bandaseaindoneshia":"Banda Sea, Indoneshia",
"bookagain":"Buku lagi",
"support&faqs":"Dukungan & FAQS.",
"hellohowcanwehelpyou":"Halo! Bagaimana kami dapat membantu Anda?",
"presstheheartbuttontoaddanhotel":"Tekan tombol Jantung untuk menambahkan hotel.",
"paymentsanddiscountfees":"Pembayaran dan biaya diskon",
"totamremaperiam":" Totam Rem Aperiam.",
"sedquiaconsequunturmagni":" Sed Quia Consome Magni",
"nequeporroquisquamest":"Neque porro quisquam est",
"aliquamquaeratvoluptatem":"Aliquam quaerat voluptatem.",
"bookinginformation":"Pemesanan informasi",
"profile":"Profil",
"johnblake":" John Blake.",
"editprofile":"Sunting profil",
"basicdetail":"Detail dasar",
"name":"Nama",
"dateofbirth":"Tanggal lahir",
"phonenumber":"Nomor telepon",
"male":"Pria",
"female":"Perempuan",
"filters":"Filter",
"ridehistory":"Naik sejarah",
"help":"Membantu",
"logout":"Keluar",
"favoriteplaceinthearea":"Tempat favorit di daerah tersebut",
"reviewdetail":"Tinjau detail",
"wedjan":"Rabu Januari",
"thujan":"Thu.",
"jhondoe":"Jhon doe.",
"enterthepasswordforsecureyouraccount":"Masukkan kata sandi untuk Aman \n akun Anda.",
"entertheemailaddressassociatedwithyouraccount":"Masukkan alamat email yang terkait dengan akun Anda.",
"backto":"Kembali ke",
"register":"Daftar",
"leaseenteravalidfirstname":"Sewa Masukkan nama depan yang valid",
"pleaseenteravalidlastname":"Silakan masukkan nama belakang yang valid",
"pleaseenteravalidemailaddress":"Silakan isi alamat email",
"pleaseenteravalidphoneno":"Silakan masukkan nomor telepon yang valid",
"pleaseselectdate":"Silakan pilih tanggal",
"restaurant":"Restoran",
"onesingleroomx2nights":"Satu kamar tunggal x 2 malam",
"menu":"Tidak bisa",
"favorite":"Favorit",
"seeall":"Lihat semua",
"pleaseenteravalidusername":"Silakan masukkan nama pengguna yang valid",
"pleaseenteradateofbirth":"Silakan masukkan tanggal lahir",
"pleaseentervalidmobilenumber":"Silakan masukkan nomor ponsel yang valid",
"myprofile":"Profil saya",
"views":"Tampilan",
"selectyourpreferredlanguage":"Pilih bahasa pilihan Anda",
"confirmlanguage":"Konfirmasi bahasa.",
"termsandcondition":"Syarat dan ketentuan",
};
