final Map<String, String> ruTranslation = {
"message":"Message",
"hotelbooking":"Бронирование отеля",
"skip":"Пропускать",
"selectdestination":"Выберите пункт назначения ...",
"next":"Следующий",
"pickupyourtime":"Забрать свое время ...",
"enjoyyourtrip":"Наслаждайтесь вашим путешествием...",
"start":"Начинать",
"welcome":" Добро пожаловать",
"haveaaccountsignin":"Есть аккаунт? Войти",
"login":"Авторизоваться",
"signup":"Зарегистрироваться",
"password":"Пароль",
"forgotpassword":"Забыл пароль?",
"or":"Или",
"donthaveanaccount":"У вас нет аккаунта?",
"username":"Имя пользователя",
"mobilenumber":"Номер мобильного",
"alreadyhaveanaccount":"Уже есть аккаунт?",
"send":"Отправить",
"backtologin":"Вернуться на страницу входа",
"verifyyouremail":"Подтвердите Ваш электронный адрес",
"checkyourmail":"Проверь почту",
"wehavesentaotptoyourmailpleaseverify":"Мы отправили OTP на вашу почту \n, пожалуйста, проверьте",
"verify":"Проверять",
"createnewpassword":"Создать новый пароль",
"newpassword":"новый пароль",
"conformpassword":"Соответствовать паролю",
"save":"Сохранять",
"choosethelanguage":"Выберите язык",
"english":"английский",
"french":"Французский",
"gujarati":"Гуджарати",
"germany":"Германия",
"italian":"Итальянский",
"belize":"Белизны",
"polish":"Польский",
"brazil":"Бразилия",
"hithomas":"Привет Томас,",
"findyourhotel":"Найдите свой отель",
"trysingapore":"Попробуйте Сингапур",
"nearyou":"Рядом с тобой",
"singapore":"Сингапур",
"turkey":"Турция",
"amsterdam":"Амстердам",
"discover":"Обнаружить",
"viweall":"Viwe все",
"visited":"Посещение",
"india":"Индия",
"grandhyatt":"Гранд Hyatt.",
"onmap":"На карте",
"centralareasingapore":"Центральная область, Сингапур",
"carltoncityhotel":"Carlton City Hotel.",
"km":"км",
"night":"Ночь",
"roomavailable":"Комната доступна",
"details":"Подробности",
"sheratonhotel":"Sheraton Hotel.",
"maubstreetchicagoil":"Улица Моб, Чикаго, Ил",
"pernight":"за ночь",
"review":"Рассмотрение",
"facilities":"Удобства",
"wifi":"вай-фай",
"gym":"Спортзал",
"pool":"Бассейн",
"restourant":"Реконструировать",
"parking":"Стоянка",
"itisalongestablishedfactthatareaderwillbeadistractedbythereadablecontentofapagewhenlookingatitslayoutthepointofusingloremofaipsumisthatithasamoreorlessnormalnormaldistributionofletters":"Долго установлен факт, что читатель будет отвлекаться на читаемый контент страницы при рассмотрении его макета. Точка использования LOREM IPSUM заключается в том, что она имеет более или менее нормальное нормальное распределение букв.",
"booknow":"Забронируйте сейчас",
"jademountainhotel":"Jade Mountain Hotel.",
"price":"Цена",
"search":" Поиск",
"booking":" Бронирование",
"standardsingleroom":"Стандартный одноместный номер",
"fastname":"Быстрое имя",
"lastname":"Фамилия",
"email":"Эл. адрес",
"phoneno":"Телефонный номер.",
"arrival":"Пребытие",
"departure":"Вылет из",
"viewdetails":"Посмотреть детали",
"additionalservice":"Дополнительное обслуживание",
"spa":"спа",
"payment":"Оплата",
"onesingleroomnights":"Один одноместный номер Ночей",
"total":"Всего",
"addnewaddress":"Добавьте новый адрес",
"homelocation":"Домашнее местоположение",
"prospectsaintjamesbarbadosn/a":"Перспектива, Святой Джеймс, Барбадос Н / А",
"selectcard":"Выберите карту",
"creditcard":"Кредитная карта",
"paypal":"PayPal",
"applepay":"Apple Pay.",
"pay":"Платить",
"addcreditcard":" Добавить кредитную карту",
"cardholdername":"Имя владельца карты",
"stefanjohn":"Стефан Джон",
"cardnumber":"Номер карты",
"cvv":"CVV",
"expirationdate":"Срок годности",
"securitycode":"Код безопасности",
"done":"Сделанный",
"yourcardhasbeenaddedsuccessfully":"Ваша карта была успешно добавлена",
"january":"Январь",
"february":"Февраль",
"checkin":"Регистрироваться",
"checkout":"Проверить",
"jan":"Январь",
"grandcity":"Гранд Сити",
"carltoncity":"Карлтон Сити",
"reviews":"Отзывы",
"thomashenderson":"Томас Хендерсон",
"des":"Дес",
"loremipsumdolorsitametconsecteturadipiscingelitleonequeloremettortor":"Лорема Ipsum Dolor Sit Amet, конспект Adipiscing Elit. Лео Нек Лорем и Теркут.",
"recommended":"рекомендуемые",
"filter":"Фильтр",
"reset":"Сброс настроек",
"category":"Категория",
"all":"Все",
"popular":"Популярный",
"sale":"распродажа",
"luxury":"Роскошь",
"pricerange":"Ценовой диапазон",
"rating":"Рейтинг",
"freewifi":"Бесплатный вай-фай",
"parkingarea":"Парковка",
"breakfirstmenu":"Breakfirst меню",
"bedroom":"спальная комната",
"showresult":"Показать результат",
"notification":"Уведомление",
"yourappoinmentisbooked":"Ваше приспоминательство забронировано",
"min":"мин",
"loremipsumissimplydummytextoftheprintingindustry":"Lorem Ipsum - это просто манекен текст печатной промышленности.",
"hour":"Час",
"hrs":"HRS",
"day":"День",
"chooseroom":"Выберите комнату",
"freecoffee":"Бесплатный кофе",
"freebreakfast":"Бесплатный завтрак",
"roseroom":"Розовая комната",
"ndfloor":"ND этаж",
"loremipsumdolorsitametconsecteturadipiscingelitmuspurusdictumarcutinciduntsitetiamegetquammattisleomaurisdignissimturpisnibhatfeugiatblanditcursusfermentumultriciesnecnislnasceturturpisfacilisisodalesvariuslacuserosetiamturpisipsumvitaedonec":"Лорема Ipsum Dolor Sit Amet, конспект Adipiscing Elit. Mus Purus Dictum Arcutincidunt сидит etiam eget quam. Mattis Leo Mauris, Dignissim Turpis Nibh. В Fegiat Blandit Cursus Fermentum Ultricies NEC NISL. Nascetur Turpis Facilisi Sodales Varius Lacus.eros etiam Turpis Ipsum Vitae Donec.",
"howlong":"Сколько",
"addreview":"Добавить отзыв",
"giveyourgrades":"Дайте свои оценки",
"whatdoyousay":"Что ты говоришь ?",
"whatdoyouthink":"Как вы думаете ?",
"notrecommended":"Не рекомендуется",
"settings":"Настройки",
"basic":"Базовый",
"account":"Счет",
"privacy&security":"Конфиденциальность и безопасность",
"location":"Место нахождения",
"darkmode":"Темный режим",
"more":"Более",
"language":"Язык",
"terms&condition":"Условия и состояние",
"customerservice":"Обслуживание клиентов",
"signout":"Выход",
"aboutus":"О нас",
"contactinformation":"Контакты",
"companyaddress":"Адрес компании",
"ithassurvivednotonlyfivecenturiesbutalsotheleapintoelectronictypesettingremainingessentiallyunchangeditwaspopularisedinthe1960swiththereleaseofletrasetsheetscontainingloremipsumpassagesandmorerecentlywithdesktoppublishingsoftwarelikealduspagemakerincludingversionsofloremipsum":"Он выжил не только пять веков, но и прыжок в электронные наборники, оставаясь по существу без изменений. В 1960-х годах он был популярен в 1960-х годах с выпуском листов LETRARASET, содержащих проходы LOREM IPSUM, а совсем недавно с программным обеспечением для публикации настольных компьютеров, таких как Aldus PageMaker, включая версии LOREM IPSUM.",
"privacypolicy":"Политика конфиденциальности",
"utenimadminimaveniamquisnostrumexercitationnemullamcorporissuscipitlaboriosamnisiutaliquidexeacommodiconsequaturquisautemveleumiurereprehenderitquiineavoluptatevelitessequamnihilmolestiaeconsequaturvelillumquidoloremeumfugiatquovoluptasnullapariatur":"Ut enim ad minima eniam, quis nostrum whereatitionnem Ullam CORFORS SUSCIPIT MALDIOSAM, NISI UT ALIQUIDEX EA Commodi Sightatur? Quis autem vel eum iurereprehenderit qui в советник Прутвета Велит Эсс-Квам-Нигил Молистия Последующая, Велет Иллам Куи Долорема Eum Fugiat Quo Voluthas Nulla Pariatur?",
"iagreewiththetermsandcondiition":"Я согласен с условиями и конденсацией",
"iagreewiththeprivacypolicy":"Я согласен с политикой конфиденциальности",
"accept":"Принимать",
"decline":"Отклонить",
"favourite":"Любимый",
"thegreathyatt":"Великий Гитт",
"marinabaysingapore":"Марина Бэй, Сингапур",
"paymentcompleted":"Оплата завершена",
"history":"История",
"ritzcarlton":"Ритц-Карлтон",
"bandaseaindoneshia":"Банда Море, Индонесия",
"bookagain":"Забронировать",
"support&faqs":"Поддержка и часто задаваемые вопросы",
"hellohowcanwehelpyou":"Привет! Как мы можем тебе помочь?",
"presstheheartbuttontoaddanhotel":"Нажмите кнопку сердца, чтобы добавить отель.",
"paymentsanddiscountfees":"Платежи и скидка",
"totamremaperiam":" Тотам Рем Апериам",
"sedquiaconsequunturmagni":" Sed Caia Следствием Магни",
"nequeporroquisquamest":"Неque porro Quisquam EST",
"aliquamquaeratvoluptatem":"Аликем Querat Voluthatem.",
"bookinginformation":"Бронирование информации",
"profile":"Профиль",
"johnblake":" Джон Блейк",
"editprofile":"Редактировать профиль",
"basicdetail":"Основные детали",
"name":"Имя",
"dateofbirth":"Дата рождения",
"phonenumber":"Телефонный номер",
"male":"Мужчина",
"female":"Женский",
"filters":"Фильтры",
"ridehistory":"История езды",
"help":"Помощь",
"logout":"Выйти",
"favoriteplaceinthearea":"Любимое место в этом районе",
"reviewdetail":"Обзор подробно",
"wedjan":"Ср. Январь",
"thujan":"Чун",
"jhondoe":"Джон Доу",
"enterthepasswordforsecureyouraccount":"Введите пароль для защищенного \n Вашей учетной записи.",
"entertheemailaddressassociatedwithyouraccount":"Введите адрес электронной почты, связанный с вашей учетной записью.",
"backto":"Вернуться к",
"register":"регистр",
"leaseenteravalidfirstname":"Аренда Введите правильное имя",
"pleaseenteravalidlastname":"Пожалуйста, введите действительный фамилия",
"pleaseenteravalidemailaddress":"Пожалуйста, введите действительный адрес электронной почты",
"pleaseenteravalidphoneno":"Пожалуйста, введите действительный номер телефона",
"pleaseselectdate":"Пожалуйста, выберите Дата",
"restaurant":"Ресторан",
"onesingleroomx2nights":"Одна комната х 2 ночей",
"menu":"меню",
"favorite":"Любимый",
"seeall":"Увидеть все",
"pleaseenteravalidusername":"Пожалуйста введите действительное имя пользователя",
"pleaseenteradateofbirth":"Пожалуйста, введите дату рождения",
"pleaseentervalidmobilenumber":"Пожалуйста, введите действительный номер мобильного телефона",
"myprofile":"Мой профайл",
"views":"Просмотры",
"selectyourpreferredlanguage":"Выберите ваш предпочтительный язык",
"confirmlanguage":"Подтвердите язык",
"termsandcondition":"Сроки и условия",
};
